### ISSUE TITLE
Fix uploading manuscripts on review environments

### ISSUE THREAD

**Issue by damnhipster** [elifesciences/elife-xpub#1064]
Review environments only support xpub up to the point of uploading a manuscript. Review environments need integration with an S3 endpoint for manuscript upload to function correctly.

## Tasks
- [x] create temporary test environment from Helm chart
- [x] reproduce problem and ensure the error is visible
- [x] fiddle with it adding a container simulating S3
- [x] configure app in `ci` to talk to `fakes3` as an endpoint
- [x] add a new stage to the formula build that does some validation

**Comment by damnhipster** [comment]
Closed in favour of #1100

**Comment by damnhipster** [comment]
Reopened to be implemented on Jenkins rather than Gitlab

**Comment by giorgiosironi** [comment]
https://alfred.elifesciences.org/job/test-elife-xpub/537/ is broken on `elife-xpub--ci`, I think because the `ci` environment is overloaded with running the Helm chart and also this stack. To be fair we could drop `elife-xpub--ci`, cutting one stack from the pipeline and relying on `end2end` and `staging` as testing environments.

`elife-xpub--ci` only runs some smoke tests, and `elife-xpub` tests are run on `develop` by the oddly named https://alfred.elifesciences.org/job/test-elife-xpub-source-repository/ so `end2end` would become the first place where we test `elife-xpub-deployment`+`elife-xpub-formula`. Thoughts?

**Comment by diversemix** [comment]
Sounds reasonable to me. Thinking about the testing strategy... this sounds like a good place to run integration tests too. Or do we want them running in CI ?

**Comment by damnhipster** [comment]
Integration tests on CI still sound reasonable to me, since we can clear state easily enough when running local mocks. 

The review environment will be using a combination of real endpoints and containerised fakes, which we'll probably need to have a way to setup and destroy/clear.

Or we rewrite the tests so the test data is unique for each test, which feels like a lot of work.

**Comment by giorgiosironi** [comment]
> integration tests

What is the definition of "integration" in here? `end2end` and `staging` do integration with everything we can, from real services (EC2 instances, ELB, S3 buckets, RDS, Fastly) to other projects (`journal`, `api-gateway`, `journal-cms`).

https://alfred.elifesciences.org/job/test-elife-xpub-source-repository/ (driven by `elife-xpub`) seems to cover running all the tests that are in the project, it could also produce a `develop` review environment identical to the PRs one if we want.
https://alfred.elifesciences.org/job/test-elife-xpub/ (driven by `elife-xpub-deployment`) will now cover `end2end` and `staging`, running `elife-spectrum` end2end tests.

**Comment by giorgiosironi** [comment]
I'm redeploying a PR to check how review environments are working now.

**Comment by giorgiosironi** [comment]
Review environments on Jenkins haven't changed much, work in general but break on manuscript uploads.
The error is different:
```
{"data":null,"errors":[{"message":"connect ECONNREFUSED 127.0.0.1:41051","locations":[{"line":2,"column":3}],"path":["uploadManuscript"]}]}
```

**Comment by damnhipster** [comment]
> > integration tests
> 
> What is the definition of "integration" in here? `end2end` and `staging` do integration with everything we can, from real services (EC2 instances, ELB, S3 buckets, RDS, Fastly) to other projects (`journal`, `api-gateway`, `journal-cms`).

The integration tests in xpub are where we are testing multiple units of code as groups. It's not supposed to test the integration with external systems, but right now, the tests do a combination of both.

**Comment by damnhipster** [comment]
> Review environments on Jenkins haven't changed much, work in general but break on manuscript uploads.
> The error is different:
> 
> ```
> {"data":null,"errors":[{"message":"connect ECONNREFUSED 127.0.0.1:41051","locations":[{"line":2,"column":3}],"path":["uploadManuscript"]}]}
> ```

I think [this](https://github.com/elifesciences/elife-xpub/pull/1117/commits/b07650cb6fc0a315218b44c9c47be64a7210f4cf) needs to be reverted.

**Comment by giorgiosironi** [comment]
Executing 
```
NODE_CONFIG_ENV=ci node -e "const c = require('config'); console.log(JSON.stringify(c.get('aws'), null, 4));"
```
in the pod gives:
```
{
    "credentials": {
        "region": "",
        "accessKeyId": "",
        "secretAccessKey": ""
    },
    "s3": {
        "s3ForcePathStyle": true,
        "params": {
            "Bucket": "dev-elife-xpub"
        },
        "endpoint": {
            "protocol": "http:",
            "host": "localhost:57575",
            "port": 57575,
            "hostname": "localhost",
            "pathname": "/",
            "path": "/",
            "href": "http://localhost:57575/"
        }
    }
}
```
where the port number is randomly generated, so I think this is picking up https://github.com/elifesciences/elife-xpub/blob/develop/config/test.js#L35 for some reason?

**Comment by giorgiosironi** [comment]
Sorry, I meant:
https://github.com/elifesciences/elife-xpub/blob/963e51318fb0afccbb2712241c15c72a99a87bba/config/ci.js#L8
which can't work in the review environment because the port is fixed. If we use `ci` only to run review environments and `test` only to run tests with `docker-compose`, we could change it?

**Comment by damnhipster** [comment]
You're correct @giorgiosironi. 

Reverting [this commit] should fix the issue, as it hardcodes the host and port for fakes3 in CI.

**Comment by giorgiosironi** [comment]
Last thing before closing is https://github.com/elifesciences/elife-xpub-formula/pull/62 where I am testing running an `helm lint` command on the formula for minimal validation.

**Comment by giorgiosironi** [comment]
![ec87daa6-752f-4fe4-93b3-3189eb98f767](https://user-images.githubusercontent.com/160299/49235240-93f86e80-f3f1-11e8-82ac-34bda8752172.png)

**Comment by giorgiosironi** [comment]
Close if satisfied.

**Comment by diversemix** [comment]
@giorgiosironi / @damnhipster  Can someone explain why the port needs to be fixed ... it works on my machine! :)

**Comment by diversemix** [comment]
@damnhipster ... FTR we should not be re-opening issues. (see: https://github.com/elifesciences/elife-xpub/blob/develop/CONTRIBUTING.md )

**Comment by giorgiosironi** [comment]
> why the port needs to be fixed

Not sure what combinations of configuration files and environments you were running locally, but the Helm chart that uses `ci` has a [fixed port](https://github.com/elifesciences/elife-xpub-formula/blob/master/helm/elife-xpub/templates/deployment.yaml#L73) for the `fakes3` container.

So `ci` needed to always use that port rather than a random one; afaik the random port would be used in automated tests to run another S3 simulator, but all tests should be running with the `test` config rather than with `ci`.

**Comment by damnhipster** [comment]
> https://github.com/elifesciences/elife-xpub/blob/develop/CONTRIBUTING.md

I think it comes under 'Closed under error', given that the work to "fix uploading manuscripts on review environments" still had to be done which I hadn't realised at the time, regardless of whether they're on Jenkins or Gitlab.

**Comment by diversemix** [comment]
I'm confused ... I thought we removed CI ?

**Comment by damnhipster** [comment]
We removed the CI environment since it was only responsible for running some smoke tests and making sure the app started up successfully. The e2e environment gives us that coverage already, so getting rid of it means one less environment to maintain.

The CI config still gets used by the review environments spun up using Helm. We can look at renaming things to `review` to make it clearer.

**Comment by giorgiosironi** [comment]
> The CI config still gets used by the review environments spun up using Helm. We can look at renaming things to review to make it clearer.

If it helps, the process is to add the `review` config; deploy; switch the chart to use `review`; remove `ci` config.

**Comment by damnhipster** [comment]
Captured remaining work in #1153
