### ISSUE TITLE
Dropdown component updates (mobile)

### ISSUE THREAD

**Issue by chugginselifesciences** [elifesciences/elife-xpub#1068]
The dropdown menu used 768px and below to represent the side menu in static pages and dashboard tabs needs some visual improvements.

## Tasks

- [ ] Correct grey border/stroke on bottom of dropdown component
- [ ] Fix arrow position when menu is open
- [ ] Add padding/space above top menu item and below last menu item
- [ ] Fill viewport with menu

**1. Correct grey border/stroke on bottom of dropdown component**

When the menu is open, the border at the bottom of the dropdown component is too dark a grey. It should be `colorBackgroundHue`

![image](https://user-images.githubusercontent.com/41907215/48712754-73b4fc80-ec06-11e8-9520-3071017d6b4d.png)

**2. Fix arrow position when menu is open**

The arrow currently moves up when open - it should remain in the same position (needs to be 2px lower)

![image](https://user-images.githubusercontent.com/41907215/48712823-a4953180-ec06-11e8-8de3-a9e7ddbe75c7.png)

**3. Add padding/space above first menu item and below last menu item**

See #974 

**4. Fill viewport with menu**

Currently the dropdown for dashboard tabs only has two menu items, so much of the dashboard is still visible when the menu is open. The intention was for it to appear to fill the viewport on small devices.

Current vs design
![image](https://user-images.githubusercontent.com/41907215/48713164-9267c300-ec07-11e8-8769-74d76094db07.png)
