### ISSUE TITLE
change PeoplePickerModal to its own page with its own route

### ISSUE THREAD

**Issue by jsms90** [elifesciences/elife-xpub#1081]
(In order to complete #635)

## Subtasks
- [ ] Add People Picker route within Editors step
- [ ] Remove Modal from PP Control & change what happens on PersonPod.SelectButton click - user should be linked to new PP page
- [ ] When user clicks 'Add' inside People Picker, should redirect to Editors Page
