### ISSUE TITLE
End2end test for EJP integration

### ISSUE THREAD

**Issue by giorgiosironi** [elifesciences/elife-xpub#1171]
## Problem / Motivation

- WHO wants this? Product managers and developers 
- WHEN and WHERE do they want it? As an automated test to be executed in the `end2end` environment
- WHAT do they want? An automated test checking the successful delivery to EJP of the initial submission
- WHY do they want this? To have fewer headaches when deploying a change in a real environment like `prod`

---

## Tasks

- [x] [Complete initial submission end2end test](https://github.com/elifesciences/elife-spectrum/pull/154/files)
- [x] Provide pillar configuration for sftp server on `end2end`: [EC2](https://github.com/elifesciences/builder-configuration/pull/26), [Vagrant](https://github.com/elifesciences/elife-xpub-formula/pull/66)
- [x] Run an sftp server on `elife-xpub--end2end--1`
- [x] [Open](https://github.com/elifesciences/builder/pull/439) sftp server port
- [x] [Enable](https://github.com/elifesciences/elife-xpub/pull/1276) MECA upload from `elife-xpub--end2end` instance
- [x] Mount volume from host into `sftp` container
- [x] Expose access to the volume through a new `nginx` virtual host
- [x] [Expose](https://github.com/elifesciences/builder/pull/441) `nginx-public-folders` through a public hostname on host 1
- [x] [Check correct upload](https://github.com/elifesciences/elife-spectrum/pull/158) with `elife-spectrum`

**Comment by diversemix** [comment]
What is port 2222 for?

**Comment by giorgiosironi** [comment]
Port 22 is taken by the host SSH daemon, while the testing SFTP server binds to 2222 on the host (forwarded to 22 on that container).

**Comment by diversemix** [comment]
Looks great :+1:  let's get it in  )
