### ISSUE TITLE
Multiple file upload improvements (post MVP?)

### ISSUE THREAD

**Issue by chugginselifesciences** [elifesciences/elife-xpub#1194]
A list of suggested improvements to multiple file upload in the initial submission wizard. 

**Initial design work here:**

desktop: https://invis.io/DWOHZU3QCTX and 
mobile: https://invis.io/T2ODLC0RG3Q

- [ ] show validation text when pressing "next" while files are uploading (see below)

- [x] #1197 Show a "Supporting files" header above the list of files (replace "add supporting files" link

- [ ] Keep "Remove all" to bottom right when max 10 files are uploaded (should be addressed as part of #1165 

- [x] #1196 Show "max 10 files uploaded" validation text after submit when attempting to add more than 10 files. Currently waits until all files are uploaded before showing validation text

- [ ] When removing all files the label should change to say "Add supporting files (optional)" - it should no longer include the word "more" if no files have been added

- [ ] check styling of tick icon and spinner - the tick icon looks too thin a stroke compared to the spinner (should be 2px stroke). I can supply SVG if needed.

**Postponed/non-MVP updates (see InVision prototypes):**

- [ ] delete/remove files individually (keep "remove all" option)
- [ ] show upload progress
- [ ] show "queued" state
- [ ] replace original file when uploading files with the same filename (with modal)
- [ ] error states

**Screenshots:**

validation text, queued state

![image](https://user-images.githubusercontent.com/41907215/49879181-551add80-fe21-11e8-8e61-bbdb661299d4.png)

"Supporting files" label, uploading state, queued state
![image](https://user-images.githubusercontent.com/41907215/49879319-a0cd8700-fe21-11e8-9a10-17f4c8e09896.png)

thicker icon stroke, individual trash icons, error state etc.

![image](https://user-images.githubusercontent.com/41907215/49879132-34528800-fe21-11e8-8c77-c7186bafe40a.png)

"replace file?" modal:
![image](https://user-images.githubusercontent.com/41907215/49879368-bb9ffb80-fe21-11e8-93c1-e85e850a672b.png)
