### ISSUE TITLE
Migrate repo to GitHub and set up CI repo on GitLab.com

### ISSUE THREAD

**Issue by g-sam** [elifesciences/elife-xpub#121]

**Comment by giorgiosironi** [comment]
As per https://elifesciences.atlassian.net/browse/ELPP-3628 I just created https://github.com/elifesciences/elife-xpub-deployment with the same permissions, https://github.com/elifesciences/elife-xpub will soon be freed of the existing repository and enable this.

**Comment by jsms90** [comment]
- [x] Set up new repo on gitlab.com: https://gitlab.com/elifesciences/elife-xpub
- [x] Copy over Kubernetes cluster details (CI/CD -> Kubernetes -> Kubernetes Cluster Details 'Expand')
- [x] Copy over environment variables (Settings -> CI/CD -> Secret Variables 'Expand')

**Comment by diversemix** [comment]
@jsms90 Why is this blocked?

**Comment by tamlyn** [comment]
Blocked because @g-sam is the only person who understands all this stuff and he's on holiday.

**Comment by diversemix** [comment]
@g-sam Can we close this now?
