### ISSUE TITLE
Add Google Analytics to the page

### ISSUE THREAD

**Issue by hem-brahmbhatt** [elifesciences/elife-xpub#1341]
Add Google Analytics tags to all client-facing pieces of the application.

## Background
See #1077

## Tasks
- [ ] add Demo tag to the page on Staging environment
- [ ] add Production tag to the page on Production environment
- [ ] ensure Google Analytics is working correctly with @hdrury1

## Technical notes

We should be able to put the tag within the `<head>` tag by editing [this file](https://github.com/elifesciences/elife-xpub/blob/develop/app/index-production.html).

The only difference between the Demo and Production tags is the ID. We have a way to [load config from the server on page load](https://github.com/elifesciences/elife-xpub/blob/develop/app/index-production.html#L10), so we should be able to switch between Demo and Production IDs easily enough.

#### Demo tag
```html
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-132441389-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-132441389-2');
</script>
```

#### Production tag
```html
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-132441389-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-132441389-1');
</script>
```

**Comment by SemraSh** [comment]
The demo setup is set for staging, so this pr needs to be merged in order to be tested.

**Comment by SemraSh** [comment]
closed by #1352
