### ISSUE TITLE
Show progress animation for manuscript upload

### ISSUE THREAD

**Issue by dryhten** [elifesciences/elife-xpub#135]
- [x] Allow the server to push messages to the client #312
- [x] Report upload progress for manuscript #313
- [x] Report file processing progress for manuscript #314

**Comment by diversemix** [comment]
Ah yes ... even it we did not know the file size from the HTTP headers ...  we could always make a separate HTTP HEAD request?

**Comment by tamlyn** [comment]
Well this is in the upload, but I just checked and you do get a `Content-Length` header with the request size.

**Comment by hdrury1** [comment]
Just wanted to add a comment here following a brief discussion with @diversemix IRL. Manuscript upload progress should take into account semantic extraction, so that the title has been populated on the next screen of the wizard by the time the user accesses it. Said extraction should be dependent on some sort of time out- if the title has not been extracted after, say, 20 secs then the app feeds back to the user and they will have to enter the title themselves. Thoughts welcomed when we get to this.

**Comment by tamlyn** [comment]
Discussing this with Daniel, there's no simple way to get progress from GROBID. The best we could do is report each step in the ScienceBeam pipeline but with only three steps and conversions sometimes taking over a minute, this is probably not enough.

However it may be possible to speed up the conversion by specifying which fields we are interested in. Extracting just the title should be faster than processing the whole manuscript. We could then do a second pass at it to get all the fields as a background job.

After seeing how much this improves the processing speed, we can develop a heuristic progress animation based on the size of the file. For example start animating from 0% until upload completes then jump to 50% and continue animating slowly and jump to 100% when it's all complete.

**Comment by hdrury1** [comment]
See work Daniel has been undertaking this week: https://github.com/elifesciences/sciencebeam/pull/53 

Where does this leave us @tamlyn with regards this issue?

**Comment by tamlyn** [comment]
See updated description and new tickets

**Comment by dryhten** [comment]
A quick update on this one: it seems that we receive the file in chunks of 64K, which is still fine by me (updating the file upload progress every 64KB of data).

Since we use apollo-upload-server, the files size is not passed down to the resolver (we could still look at the file header in binary, knowing the file type, some files might include total size there, but it's too complicated imo). An easier solution would be to send the file size separately (like I did in https://github.com/elifesciences/elife-xpub/pull/368).

Usually we shouldn't trust the client to send us the right file size (that's why apollo-upload-server doesn't do it as well), but since this is used only for the animation of the upload icon, if the client sends a bad file size on purpose then it's not a problem if the animation is broken for him.
