### ISSUE TITLE
Separate the client and server config variables

### ISSUE THREAD

**Issue by SemraSh** [elifesciences/elife-xpub#1353]
Currently all the variables are stored in the same config file and if that variable is used in the client side we need to define `isPublic: true` alongside the variable. It will be better if we put the server and client side configs in separate files.

#### current version 
/config/environment 
```js
someClientConfig: {
    "exposed",
    isPublic: true
}

someServerConfig : "verySecret"
```

#### requested implementation
/server/config/environment
```js
someServerConfig : "verySecret"
```
/client/config/environment
```js
someClientConfig: "exposed"
```

## Subtasks
- [ ] Create 2 new configs one for client one for server
- [ ] Move all the client variables to the client config
- [ ] Move all the server variables to the server config

**Comment by diversemix** [comment]
Good ticket - let's discuss before anything is implemented

**Comment by hdrury1** [comment]
@diversemix and @Cooryd worth considering as part of the refactor?
