### ISSUE TITLE
Preemptively upgrade Postgres to 10.6 before AWS does it for you when you least expect it

### ISSUE THREAD

**Issue by giorgiosironi** [elifesciences/elife-xpub#1380]
Deadline: 2019-02-05

<blockquote>
Our records indicate that you have one or more PostgreSQL database instances which are not running the latest minor versions of PostgreSQL available on RDS.

Since PostgreSQL versions 10.6, 9.6.11, 9.5.15, and 9.4.20 contain important cumulative security fixes, we recommend that you upgrade your PostgreSQL 10.x instances to 10.6, PostgreSQL 9.6.x instances to PostgreSQL 9.6.11, PostgreSQL 9.5.x instances to PostgreSQL 9.5.15, and PostgreSQL 9.4.x instances to PostgreSQL 9.4.20 at your earliest convenience.

Beginning February 5, 2019, if your database instances have the “Auto Minor Version Upgrade” option enabled, we will automatically upgrade your PostgreSQL 9.4.x instances to PostgreSQL 9.4.20, PostgreSQL 9.5.x instances to PostgreSQL 9.5.15, PostgreSQL 9.6.x instances to PostgreSQL 9.6.11, and PostgreSQL 10.x instances to PostgreSQL 10.6 during your maintenance window. Depending on other maintenance activities scheduled during your maintenance window, it could take several weeks before your instance is upgraded.

As we are transitioning to the self-service model using the DB instance maintenance process[1], we will not be sending these notifications going forward. You can manage the minor version upgrade process via the AWS console or through the describe-pending-maintenance-actions command in the AWS CLI. You will also receive an RDS event notification[2] when a minor version upgrade is available for the DB instance.

Your impacted DB instances in the US-EAST-1 Region are listed below:
elife-xpub-prod
elife-xpub-staging
elife-xpub-end2end

Your instances will become unavailable for a few minutes during the upgrade, for both Single-AZ and Multi-AZ deployments.

To learn more about upgrading minor versions in Amazon RDS, review the “Upgrading Database Engine Versions”[3].

Information about supported engine versions and the Amazon RDS Deprecation policy is described on the Amazon RDS FAQs page[4].

Should you have any questions or concerns, the AWS Support Team is available on the community forums and via AWS Premium Support[5].

[1] https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.Maintenance.html
[2] https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_Events.html
[3] https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.PostgreSQL.html
[4] https://aws.amazon.com/rds/faqs/#Database_Engine_Versions
[5] https://aws.amazon.com/support
</blockquote>

## Subtasks

Use `update_infrastructure` to perform the upgrade. Requires downtime (of minutes, they said).

- [ ] RDS Postgres 10.6 on `end2end`
- [ ] RDS Postgres 10.6 on `staging`
- [ ] RDS Postgres 10.6 on `prod`

**Comment by diversemix** [comment]
@hdrury1 ... let's do this before release :pray:

**Comment by lsh-0** [comment]
outside of xpub, most other RDS instances are still on 9.something and won't see the minor version bump, just the patch

**Comment by diversemix** [comment]
Like to take another  view on this with @hdrury tomorrow

**Comment by giorgiosironi** [comment]
```
EngineVersion

    The version number of the database engine that the DB instance uses.

    Note

    To prevent automatic upgrades, be sure to specify the full version number (for example, 5.6.13). If the default version for the database engine changes and you specify only the major version (for example, 5.6), your DB instance will be upgraded to use the new default version. Note that the default version is not necessarily the latest supported version.

    Required: No

    Type: String

    Update requires: Some interruptions
```
So we should be able to do this without backups/restores, just some minutes of downtime.

**Comment by giorgiosironi** [comment]
About to try this on `elife-xpub--end2end`.

**Comment by giorgiosironi** [comment]
Seems to have worked:
https://github.com/elifesciences/builder/pull/448
https://console.aws.amazon.com/rds/home?region=us-east-1#database:id=elife-xpub-end2end;is-cluster=false;tab=configuration
and it has kept the data:
```
elife@end2end--xpub:~$ docker run -it -e PGHOST -e PGPORT -e PGUSERNAME -e PGPASSWORD -e PGDATABASE postgres:10 psql
psql (10.5 (Debian 10.5-1.pgdg90+1), server 10.6)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

elifexpubend2end=> SELECT COUNT(*) FROM manuscript;
 count 
-------
     4
(1 row)
```

**Comment by giorgiosironi** [comment]
Applied everywhere.

**Comment by lsh-0** [comment]
cheers @giorgiosironi
