### ISSUE TITLE
Add user to AuditLog

### ISSUE THREAD

**Issue by hem-brahmbhatt** [elifesciences/elife-xpub#1391]
### Background
As an administrator
When I view the audit logs for a manuscript
I want to know who performed the actions that have been logged
So I can track changes more easily

### Related issues
Depends on #1243 

### Tasks
- [ ] Add a factory function to the AuditLog to create new records, and use this within models
- [ ] Remove references to AuditLog from within other models, and move the calls into a controller
- [ ] Record the userId of the user making changes to the model, i.e. manuscript
- [ ] Record the user making changes to the model. Add a new `user` column to AuditLog, and log the user. Examples of users are: `EJP`, `xPub`
