### ISSUE TITLE
Notify #xpub-tech of build failures

### ISSUE THREAD

**Issue by giorgiosironi** [elifesciences/elife-xpub#1543]
## Subtasks

- [x] Create [incoming webhook](https://elifesciences.slack.com/services/BG9TJTVNW?added=1) for ~`#xpub-tech`~ generic Slack channels
- [x] Introduce `elife.vault-approle` for `elife-alfred--prod`
- [x] Extend `elifeSlack` allowing a channel to be passed in
- [x] Use `elifeSlack` from `elifePipeline` to notify the channel named in `maintainers.txt`
- [x] `xpub-tech`
- [x] `profiles`
- [ ] `journal-cms`

## Assumptions and notes
- The [Jenkins Slack plugin](https://elifesciences.slack.com/messages/C6LKMFK5Z/convo/C6LKMFK5Z-1550501574.050300/) doesn't allow to configure automatically actions on imperative pipelines like `test-elife-xpub-source-repository`

**Comment by giorgiosironi** [comment]
Doing https://github.com/elifesciences/issues/issues/4755 first which may change a bit how we interact with Vault from builds.

**Comment by giorgiosironi** [comment]
<blockquote>
Channel Override
Incoming webhooks have a default channel, but it can be overridden in your JSON payload. A public channel can be specified with "channel": "#other-channel", and a Direct Message with "channel": "@username".
</blockquote>

**Comment by giorgiosironi** [comment]
We may use the same webhook as #deployments then. No need for integration with Vault for this.

**Comment by giorgiosironi** [comment]
Before executing builder tasks, `elifeFormula` needs to execute `vault.sh token lookup` to make sure its Vault token is current.

**Comment by giorgiosironi** [comment]
We can add a new specification for what should be contained in the notifications, that would be a different issue.
