### ISSUE TITLE
Controller Architecture

### ISSUE THREAD

**Issue by hem-brahmbhatt** [elifesciences/elife-xpub#1587]
Here are the notes from the _Refactoring xpub-controller_ meeting held on Tuesday 26th February 2019.

This issue encapsulates the work needed to get the server-side controllers into a state where the following problems are addressed:

1. Existing controllers are hard to test. Dependencies are not easy to mock.
2. Separation between controllers and helpers is unclear
3. Naming is difficult, given that controllers are named after models rather than logic.
4. Client interfaces are not centralised, for example, mailer and pubsub
5. No consistent way to work with models

## Talking points

- [ ] Controllers instantiate the model, and pass it around helper functions which work on the models
- [ ] Controllers call helpers to work with clients (science beam, S3, pubsub)
- [ ] helpers take models and clients as parameters
    - [ ] uploadManuscript(file, user, model)
    - [ ] endFileProgress(file, user, model)
    - [ ] const uploadManuscript = Helper.uploadManuscript.bind(file, user, model)
- [ ] clients contain S3, pubsub, APIs and other persistance
- [ ] Logging is done via controllers ?
- [ ] directory structure: controllers/manuscript/(index.js, upload.js, helpers.js)
- [ ] Investigate: Creating virtual properties on Manuscript model, for example, source file

## Issues to create
(marking off issues **made** not **completed**)
- #1590 - make a client for pubsub within xpub-controller
- #1591 - make a client for mailer within xpub-controller
- #1084 - move elife-api to client
- #1592 - create a virtual property on the model for source file
    - manuscript.sourceFile 
- #1596 - create a refresh function on models
    - returns a new instance
    - replaces Model.find usages
- #970 reduce line length

### Migrating existing controllers to the new structure
- #1609 - move `client` from the `xpub-controller` to its own top level directory alongside `xpub-controller`
- #1603 - move existing controller code into a legacy directory
- #1604 - create factory.js inside xpub-controller which is responsible for creating new model instances
- #1606 -  create the new controllers
    - #1607 - upload controllers, including progress of the upload 
    - #1611 supporting file uploads 
    - #1614 manuscript updating (needs breakdown)
        - #1615 move applyInput from manuscript model into a controller
    - email notifications
- #1606 rename manuscript controller to submission controller in the new controller

## Coding standards to follow
- name controllers after functionality/logic rather than names given to models such as Manuscript and File.
- export controllers with Controller in the name
- rename models used in controllers to include Model in the name
- unused code (such as factories) are okay to be introduced
- controllers can call other controllers ???
- try to keep dependencies to a minimum, and consider creating separate controllers instead
- ensure all new code has tests written for it

## Directory structure
```
controllers/
  manuscript/
    upload/
      index.js
      progress.js
      …
    update/
      index.js
      …
```

**Comment by diversemix** [comment]
This all looks really good, the following points may seem pedantic, but I think it would be good to:
1) *Call this as re-architecting* -to distinguish it from general refactoring work that we would normally do during our day to day development work.
2) *Never use `model`* without some sort of qualifier - in the PubSweet community this has caused a number of issues and so we should refer (and perhaps rename) things to `data-model` etc.

On the whole though this is excellent work! Thanks all!

**Comment by hem-brahmbhatt** [comment]
Closing due to https://github.com/elifesciences/elife-xpub/issues/1668
