### ISSUE TITLE
Create a client for the mailer

### ISSUE THREAD

**Issue by Cooryd** [elifesciences/elife-xpub#1591]
## Problem / Motivation
As part of the refactoring of the controller (see #1587) it would be beneficial to have a `MailerClient` class which could be accessed from the controllers client collection (same place as the `scienceBeamApi.js` and `S3Storage.js` client files).

Currently this code sits in a file/class called `Notification` found directly in the `xpub-controller` directory with missing unit tests.

### Location
```
/xpub-controller
  /client
    mailer.js
```
### Tasks

- [ ] move mailer logic within `notification.js` to `/client/mailer.js`
- [ ] make `@pubsweet/mailer` and `logger` injected dependencies similar to `config`
- [ ] make `mailer` a class with the signature `new Mailer(from, to)`
- [ ] create a `sendEmail(template, data)` function
- [ ] remove config as an injected dependency, it should no longer be needed
- [ ] use the new mailer client within `notification.js`
- [ ] write unit tests for client class (might want to do this in parallel with the refactor task, one function at a time)

### Question points

- Should the dependency of `config` be replaced with `baseUrl` being passed and stored in the constructor? (probably, one less module dependency 👍)

## Clarification needed and assumptions

This might need splitting to smaller tasks ie: relocate and rename, refactor dependencies, refactor `sendDashboardEmail()` with tests, refactor `isValidEmail()` with tests. Or you may find the refactor is manageable in one task.

**Comment by hem-brahmbhatt** [comment]
> * Should the dependency of `config` be replaced with `baseUrl` being passed and stored in the constructor? (probably, one less module dependency 👍)

The only function using the parameter is `sendDashboardEmail`, so the email has a link to the dashboard page. We can assign that to a parameter so the call looks like `await sendDashboardEmail({ dashboardLink: baseUrl })`, and the function can be `async sendDashboardEmail({ dashboardLink })`

**Comment by hem-brahmbhatt** [comment]
Note that we're also sending emails within https://github.com/elifesciences/elife-xpub/blob/develop/server/meca/routes.js#L40-L50. It would be good to use the new mailer client for this as well, but I fear that we would need to make the client more generic rather than functions like `sendDashboardEmail`, especially given #1609. We may want to split `Notification` into `controller/Notification` and `client/Mailer`, where the controller takes care of the data, and the mailer is responsible of passing the data into a given template.

**Comment by hem-brahmbhatt** [comment]
@Cooryd if you're happy with the above, I'll update the description.

**Comment by Cooryd** [comment]
I agree the client should be a generic interface with the mailer and the controller should control the content. Sounds good to me
