### ISSUE TITLE
Create entity model factory functions for creating entities, saving them to the db and returning them

### ISSUE THREAD

**Issue by Cooryd** [elifesciences/elife-xpub#1604]
## Problem / Motivation
As part of the refactoring of the controller (see #1587) we have decided to make controller functions as imported dependency free as possible. The rational is that mocking dependencies that are `require`ed in a file makes unit tests more complicated than they need to be and that using the real model classes required a full db backing the unit tests when this shouldn't be necessary with the scope of the the code being tested. 

## Proposed solution

It was decided that controller functions should call on factory functions which are passed entity model classes and templated data and then return an instance of an entity which has been pre-saved to the data base.

### Location
 These factory functions should sit in a `factory` directory inside the controller directory (alongside `client`). and be named after the entity model they are generating.

```
/xpub-controller
  /factory
    file.js
    manuscript.js
```

### Sudo-code
The function should be called something like `fileFactory()`. The factory method should be responsible for creating new FileModels as well as fetching instantiating FileModels based on existing data.

*factory code*

```
function fileFactory(FileModel, {id, ...fileData}) {
  if (id) return FileModel.find(id)
  const fileEntity = new FileModel(fileData)
  await fileEntity.save()
  return fileEntity
}
```

*future controller code*
```
const FileModel = require(...)
...
const fileEntity = fileFactory(FileModel, { type: 'SUPPORTING_FILE})
```

### Tasks
- [ ] create `fileFactory`
- [ ] tests for `fileFactory`
- [ ] create `manuscriptFactory`
- [ ] tests for `manuscriptFactory`

## Clarification needed and assumptions

Write unit tests for these factory functions, This should be relatively simple as the class is being passed as a param so you can assign `save` a  `jest.fn()` in a dummy class created for the test and passed as the first param.

This code is in preparation for the controller refactor work so these new factory functions do not need to be called anywhere within the codebase *yet*

**Comment by Cooryd** [comment]
The work for `fileFactory` has pretty much been completed in a prototype branch https://github.com/elifesciences/elife-xpub/tree/new-controller/server/new-controller/factories

**Comment by hem-brahmbhatt** [comment]
Needs updating due to https://github.com/elifesciences/elife-xpub/issues/1668, specifically the following:
- [ ] understand where factories will live
