### ISSUE TITLE
Create uploadManuscriptFile function in the new File controller class

### ISSUE THREAD

**Issue by Cooryd** [elifesciences/elife-xpub#1607]
## Problem / Motivation
As part of the refactoring of the controller (see #1587) we need to re-write the `uploadManuscriptFile` controller function which should sit in the `File` controller class.

## Proposed solution
The discussed pattern for organising the files that relate to a controller function should be as follow:

### Agreed general controller pattern rules

- Functions defined directly in the controller classes (within the `index.js`) should not directly process or fetch data. Their job is to create instance of clients, pass the correct values/ dependencies to helper functions and clients and to call the helper / client functions in the correct order. **If you find yourself writing logic inside the `index.js` of a controller, it should probably be placed in its own function file and imported as a dependency of the `index.js` so that it can be unit tested correctly.**

- Commonly used functions which can be used by multiple top level controller functions should sit along side the `index.js` file  ie: `checkFileSize()` can be used by `uploadManuscriptFile` and `uploadSupportingFile` where as functions that deal with a process specific to one top level controller function should sit in a directory with that top level functions name. ie: `clearManuscriptSourcePendingFiles()` may be specific to the `uploadManuscriptFile` controller function and used no where else

```
/xpub-controller
  ...
  /file
    index.js
    index.test.js
    checkFileSize.js
    checkFileSize.test.js
    /uploadManuscriptFile
      clearManuscriptSourcePendingFiles.js
      clearManuscriptSourcePendingFiles.test.js
```

- Processes that call off to external services / are an interface to another service should live in the top level `/client` directory of `xpub-controller` and should have external package dependencies passed on instantiation so they are simple to test. Examples of clients are: `S3Storage`, `ScienceBeamApi`, `Pubsub`, `ElifeApi`, `Mailer`

### Tasks

The following processes need to be built to form the whole `uploadManuscriptFile` controller function:

- [ ] validate file size
- [ ] fetch the manuscript entity 
- [ ] validate there are no current related files of type `MANUSCRIPT_SOURCE_PENDING`
- [ ] calculate the estimated time to complete the process
- [ ] create a `Pubsub` instance and begin publishing the estimated progress
- [ ] call `fileFactory` to create a `File` entity
- [ ] upload file to the server
- [ ] update file entity state to `UPLOADED`
- [ ] create an instance of the `S3Storage` client
- [ ] upload file to S3
- [ ] update file entity to be `STORED`
- [ ] create and instance of `ScienceBeam` client
- [ ] extract title using `ScienceBeam`
- [ ] remove existing `MANUSCRIPT_SOURCE` file
- [ ] set `MANUSCRIPT_SOURCE_PENDING` entity to `MANUSCRIPT_SOURCE`
- [ ] set manuscript title to the extracted title
- [ ] stop publishing estimated progress and publish 100% message
- [ ] return manuscript entity 
- [ ] ensure progress is stopped and `MANUSCRIPT_SOURCE_PENDING` file entity is deleted if any process that should not throw an error, throws an error (scienceBeam call may throw when it's unable to extract title but this **shouldn't** stop the upload process )

## Clarification needed and assumptions

You will likely need to break this task down as the controller is made up of a number of processes which will all need to be written and tested. To make the reviewing of this code easier it would be best to put there in in multiple PRs. Aim for individual units of properly tested code per PR instead of large chunks that require further 'coverage' to be added later.

**Comment by Cooryd** [comment]
Some of the functionality has been written already in a prototype branch:
https://github.com/elifesciences/elife-xpub/tree/new-controller/server/new-controller/file

This is an example of how the helper functions / micro-controllers should be as pure as possible with dependencies passed as params and of how the directory structure might look (although its not quite right in this branch)

**Comment by hem-brahmbhatt** [comment]
Closing due to https://github.com/elifesciences/elife-xpub/issues/1668
