### ISSUE TITLE
Create uploadSupportingFile function in the new File controller class

### ISSUE THREAD

**Issue by Cooryd** [elifesciences/elife-xpub#1611]
## Problem / Motivation
As part of the refactoring of the controller (see #1587) we need to re-write the `upload` controller function which should sit in the current `supportingFiles` controller (https://github.com/elifesciences/elife-xpub/blob/develop/server/xpub-controller/supportingFiles.js).

## Proposed solution
This function should be moved into the `FileController` as it relates to uploading a file. I believe we can do away with the need for a separate `SupportingFileController` for the time being.

The discussed pattern for organising the files that relate to a controller function should be as follow:

### Agreed general controller pattern rules

See rules outlined in #1587 and #1607 

### Tasks
- [ ] validate file size
- [ ] validate there are no more than 10 supporting files on the manuscript
- [ ] create file entity with type `SUPPORTING_FILE` using the fileFactory
- [ ] stream the file to the server (should be a shared function in the FileController also used by `uploadManuscriptFile`)
- [ ] update file status to `UPLOADED`
- [ ] create an `S3Storage` client instance and upload the file to S3
- [ ] if upload to S3 fails delete file entity
- [ ] update file entity status to `STORED`
- [ ] return file entity

## Clarification needed and assumptions

**Comment by hem-brahmbhatt** [comment]
The coding standards within https://github.com/elifesciences/elife-xpub/issues/1587 suggest we avoid using controllers being named the same as models, and instead be named after their corresponding functionalities. I suggest we call the controller `FileUpload`, and potentially `SupportingFileUpload`.

**Comment by hem-brahmbhatt** [comment]
Closing due to https://github.com/elifesciences/elife-xpub/issues/1668
