### ISSUE TITLE
Create update function in new controller class for Submission

### ISSUE THREAD

**Issue by Cooryd** [elifesciences/elife-xpub#1614]
## Problem / Motivation
As part of the refactoring of the controller (see #1587) we need to re-write the `update` controller function which should sit in the `Submission` controller class.

## Proposed solution
The discussed pattern for organising the files that relate to a controller function should be as follow:

### Agreed general controller pattern rules

Check #1607 and #1587 for details on the agreed pattern for controller functions

### Tasks

- [ ] Fetch `Manuscript` model entity
- [ ] Validate the entity has a `status` of `INITIAL`
- [ ] Store a reference to the `author` email currently stored (this will be compared to the data being applied later)
- [ ] Apply input to manuscript entity (this is currently a function called on the entity called `applyInput` as part of this milestone we'll be moving this functionality to the controller. This issue should not attempt to address this, see issue TBD)
- [ ] save the manuscript entity
- [ ] diff the old author emails with the newly set author emails
- [ ] notify any 'new' author emails using the mailer client (see #1591 as this is being refactored)
- [ ] return manuscript entity

## Clarification needed and assumptions

You may wish to split this into smaller issues ie: per task? ensure all controller functions are tested.

**Comment by hem-brahmbhatt** [comment]
Closing due to https://github.com/elifesciences/elife-xpub/issues/1668
