### ISSUE TITLE
Move applyInput from the manuscript model to the Submission update controller

### ISSUE THREAD

**Issue by Cooryd** [elifesciences/elife-xpub#1615]
**Complete #1614 first**

## Problem / Motivation
As part of the refactoring of the controller (see #1587) we need to move the logic found in the `applyInput` function found on the `Manuscript` model in `xpub-model` into the `Submission` controller where it can be used by the `update` function. 

This function currently takes form input data and transforms it into a state that the `Manuscript` entity can accept. It has been agreed that this logic should be handled by the controller.

This function has multiple processes involved so should be broken down into smaller process functions within the controller to make them easier to unit test and more re-usable.

## Tasks

- [ ] apply appropriate data directly to entity:
```
        'meta',
        'coverLetter',
        'opposedSeniorEditorsReason',
        'opposedReviewingEditorsReason',
        'previouslyDiscussed',
        'previouslySubmitted',
        'cosubmission',
        'opposedReviewersReason',
        'submitterSignature',
        'disclosureConsent',
```
- [ ] reshape suggested and opposed editors into 'teams'
- [ ] validate no opposed reviewers are also assigned as suggested 

(This is a quick breakdown, the function looks quite complicated so be sure to go through the existing code to catch everything thats going on as I've likely missed something.)

Once this functionality has been fully ported over the the controller and is being called by the update controller in place of the previous `manuscript.applyInput` (see #1614) the function may be removed from the entity model code.

**Comment by hem-brahmbhatt** [comment]
Needs updating due to https://github.com/elifesciences/elife-xpub/issues/1668
