### ISSUE TITLE
Epic: The Grand Refactor - Round 1

### ISSUE THREAD

**Issue by hem-brahmbhatt** [elifesciences/elife-xpub#1705]
# The Grand Refactor

## Architectural Decision

https://github.com/elifesciences/elife-xpub/blob/develop/docs/adr/0005-hindawi-pattern.md

## Coding standards to follow

* Follow the directory structure laid out below. A component can include client, config, server, and test (browser and functional) folders.
* Components should have a single responsibility
* Models are injected making testing easier
* Model components should have resolvers for the respective graphql API queries/mutations
* components can use other components functionality - eventually this dependant functionality needs to live inside a shared space such as PubSweet so do this sparingly!
* ensure all new code has tests written for it

## Directory structure

[The full directory structure can be found here](https://github.com/elifesciences/elife-xpub/blob/develop/docs/adr/0005-hindawi-pattern.md#overview-of-suggested-architecture-pattern)

```
/packages
  /app
  /component-dashboard
  /component-login
  /component-submission
  /component-model-manuscript
  /component-model-file
  /component-elife-ui
  ...

```

### Initial setup
- [ ] create the /packages directory and add support to the pubsweet config to pick up packages from /packages and /server
**Not sure this can be done as an issue as it mostly involves creating an empty packages directory**

### Migrating dashboard to the new structure
- [ ] #1711 create dashboard component directory with package file and import empty package to pubsweet config  
- [ ] #1712 Move client side  dashboard components into component directory
- [ ] #1714 Move server side dashboard code to component-dashbaord directory
- [ ] ~~Move dashboard config to dashboard-component directory (if there is any?)~~ Doesn't look like there is
- [ ] #1716  Implement new dashboard-component within the app

  - is there any further work/questions that we need to take into account as part of this, such as the dashboard redesign? 
  _dashboard redesign will happen after this has been completed_
### Migrating server code to the new structure (emptying the /server directory)
- [ ] create an app component, responsible for serving the react app and client-side config, and routing code for the react app
- [ ] create a meca export component
  - does this live within one of the submission wizard components?
   _yes, we should put this within the relevant submission component, under a /component-*/provider directory_
- [ ] move dupes to /tools
- [ ] create a client/providers component
  - maybe this get moved within other components instead?
  _yes, we should put this within the relevant component which needs it, under a /component-*/provider directory_
- [ ] move models to their own components, including tests and resolvers
  - each component could also include use-cases like submitManuscript
  _this is addressed in the post migration tasks_
- [ ] create a supporting files component
  - does this live within one of the submission wizard components?
  _yes, we should put this within the relevant submission component_
- [ ] create a file upload component
  - does this live within one of the submission wizard components?
  _yes, we should put this within the relevant submission component_
### Migrating client code to the new structure (emptying the app directory)
- [ ] delete the pages components from the styleguide
- [ ] create the UI component, including moving the styleguide here, as well as atoms, molecules and people picker
- [ ] create the error page component
- [ ] create the landing redirect page component
- [ ] create the login and logout components
- [ ] create the static page components
- [ ] create the submission wizard components
  - should we rename this to initial submission?
  _this needs to be discussed and finalised_
- [ ] create the thank you/confirmation component
  - does this live within submission wizard components?
  _yes_
  - could also include code to send emails?
  _there will be a provider to send emails within the submission wizard component_
### Post migration tasks
- [ ] move /assets and /static to respective components (such as the UI component)
- [ ] move /client to respective components (such as the UI component)
- [ ] move /config to respective components
- [ ] move /templates to respective component (the component which is responsible for sending emails)

**Comment by hem-brahmbhatt** [comment]
@Cooryd @jyenes I've highlighted the issues which have some questions around it. We'll want to answer these when the issues get created.

**Comment by diversemix** [comment]
@damnhipster Why do you think the meca export component is a part of submission?

**Comment by diversemix** [comment]
I'm guessing the first task is to agree the folder structure - as there is only an "example" structure shown in the ADR.

**Comment by diversemix** [comment]
I think we should mention that components should eventually become "Bounded Contexts" in a DDD sense.

**Comment by diversemix** [comment]
Not sure what is meant by "components can call other controllers" - but if this means components can use other components functionality - then this needs to eventually live in the Shared Kernel

**Comment by hem-brahmbhatt** [comment]
> @damnhipster Why do you think the meca export component is a part of submission?

If we were to make it it's own component, it would currently be a dependency used within the submission component. To stop this being a dependency, we would need to formalise an interface for it, whether that be a graphql endpoint or something else.

Currently, the fact that the meca export code is called directly by the submission wizard means that it has no need to exist as it's own domain. There's always the option to refactor it into it's own domain in the future and front it with a better interface.

For now, I think we should take steps to simplify the dependency chain between components where we can, as we'll have more similarities with Hindawi's pattern, which is a good first step.

**Comment by hem-brahmbhatt** [comment]
> I'm guessing the first task is to agree the folder structure - as there is only an "example" structure shown in the ADR.

I wasn't aware that the directory structure in the ADR was only an example. @Cooryd, @jyenes and I have been referencing this directory structure for the tasks mentioned above. If everyone's alright with it:

👍for updating the directory structure in the ADR to no longer be an example
🥇for updating this epic to contain the exact directory structure we want to follow for components

The issues for **"Migrating dashboard to the new structure"** contain the exact directory structure to implement for each issue already.

**Comment by Cooryd** [comment]
I  see this work as a multi phase thing. 

1. Get our current code into a `packages/component-xxxx` structure but don't worry if the internal grouping is quite there.
2. Refactor code (like using more `withGQL` HOCs and completely remove use-case code from the resolvers, making use of dep injection) so it matches Hindawi's style.
3. Improve code so each bound context has its own models ect so we no longer have the need for the `component-model-xxxx` packages

edit: 
2.5. Re-look at testing so we're making use of the new dependency injected use-case code and don't need as many / any tables created for unit tests 🍾

**Comment by diversemix** [comment]
Good with all the responses here... RE: meca component - I think it will become its own component in the future - but happy its stay in submission for now, if for no other reason to simplify the task. :+1:

**Comment by Cooryd** [comment]
Round 1 seems to have been finished, we will be moving onto the code refactor shortly.
