### ISSUE TITLE
Dashboard Component: Implement component-dashboard within app 

### ISSUE THREAD

**Issue by Cooryd** [elifesciences/elife-xpub#1716]
## Background

__Complete #1714 and #1712 before starting__

As part of #1705 we are slitting the apps code up into bound-context components. Work prior to this issue will have been placed in isolation into a `component-dashboard` directory in a `packages` directory but not included in the compiled app code.

## Task

This task consists of a number of steps

- [ ] Hook up the new `component-dashboard` package in place of the legacy dashboard react router and server resolver.
- [ ] Remove all legacy dashboard code from `xpub-server` and `xpub-controller` (if there is any)

- [ ] Remove the now (hopefully) un-used dashboard related code in top level `client`
- [ ] Go over tests to make sure coverage is still sufficient over the dashboard components code (we should hopefully see a slight increase). This should allow for the removal of dashboard specific resolver tests in `xpub-server` as all tests should be within `component-dashboard`.

**Comment by Cooryd** [comment]
As part of the phased refactor work the newly moved `component-` code should be put to use as soon as the new structure is put in place. This means we no longer need a 'make live' task.
