### ISSUE TITLE
Epic: The Grand Refactor - Round 3

### ISSUE THREAD

**Issue by hem-brahmbhatt** [elifesciences/elife-xpub#1717]
# The Grand Refactor

## Architectural Decision

https://github.com/elifesciences/elife-xpub/blob/develop/docs/adr/0005-hindawi-pattern.md

## Coding standards to follow

* Follow the directory structure laid out below. A component can include client, config, server, and test (browser and functional) folders.
* Components should have a single responsibility
* Models are injected making testing easier
* Model components should have resolvers for the respective graphql API queries/mutations
* components can use other components functionality - eventually this dependant functionality needs to live inside a shared space such as PubSweet so do this sparingly!
* ensure all new code has tests written for it

## Directory structure

[The full directory structure can be found here](https://github.com/elifesciences/elife-xpub/blob/develop/docs/adr/0005-hindawi-pattern.md#overview-of-suggested-architecture-pattern)

## Issues to create
- [ ] move resolvers out of models and into the components which use them
- [ ] use recompose's `withHandlers` HOC to handle user interactions
- [ ] refactor use-cases and associated helpers to follow a better pattern
- [ ] upgrade pubsweet

**Comment by hem-brahmbhatt** [comment]
What does everyone think about merging this milestone, _The Grand Refactor - Round 3_, with this one
https://github.com/elifesciences/elife-xpub/milestone/13
