### ISSUE TITLE
Login Component: Move code to component-login

### ISSUE THREAD

**Issue by Cooryd** [elifesciences/elife-xpub#1719]
## Background

As part of #1705 we plan to phase the refactoring of the app code. Round 1 involves moving the code into a `component-xxxx` directory structure and should not require the changing of much code. This issue relates to moving / grouping the login components

## Tasks

- [x] create `component-login` directory and package files (see https://github.com/elifesciences/elife-xpub/issues/1711)
- [x] move all client code into a `client` directory within `component-login` #1740 
- [x] ~~move all server code into a `server` directory within `component-login`~~
- [x] ~~hook up newly moved code to the app and make sure there are no remaining files in the wider codebase relating to this~~
- [x] move around components from ui only used by the parent component (#1747)

__Are any login related tests left over in the wider code base after? How will we deal with that?__
