### ISSUE TITLE
Static Pages Component: Move code into component-staticPages 

### ISSUE THREAD

**Issue by Cooryd** [elifesciences/elife-xpub#1720]
## Background

As part of #1705 we plan to phase the refactoring of the app code. Round 1 involves moving the code into a `component-xxxx` directory structure and should not require the changing of much code. This issue relates to moving / grouping the static pages components

## Tasks

- [ ] create `component-staticPages` directory and package files (see https://github.com/elifesciences/elife-xpub/issues/1711)
- [ ] move all client code into a `client` directory within `component-staticPages`
- [ ] move all server code into a `server` directory within `component-staticPages`
- [ ] hook up newly moved code to the app and make sure there are no remaining files in the wider codebase relating to this.

__Are any staticPages related tests left over in the wider code base after? How will we deal with that?__
