### ISSUE TITLE
Submission Component: Move code into component-submission

### ISSUE THREAD

**Issue by Cooryd** [elifesciences/elife-xpub#1721]
## Background

As part of #1705 we plan to phase the refactoring of the app code. Round 1 involves moving the code into a `component-xxxx` directory structure and should not require the changing of much code. This issue relates to moving / grouping the submission wizard components

## Tasks

- [x] create `component-submission` directory and package files (see https://github.com/elifesciences/elife-xpub/issues/1711)
- [x] move all client code into a `client` directory within `component-submission`
- [x] move all server code into a `server` directory within `component-submission`
- [x] hook up newly moved code to the app and make sure there are no remaining files in the wider codebase relating to this.

__Are any submission related tests left over in the wider code base after? How will we deal with that?__

**Comment by diversemix** [comment]
Going to close this - risking that there may still be stuff to move in (like `fake-s3` ) ... but this is the bulk of the work.
