### ISSUE TITLE
Model Components: move Manuscript model into its own component

### ISSUE THREAD

**Issue by Cooryd** [elifesciences/elife-xpub#1722]
## Background

As part of #1705 we plan to phase the refactoring of the app code. Round 1 involves moving the code into a `component-xxxx` directory structure and should not require the changing of much code. This issue relates to moving / grouping the model components

## Tasks

- [ ] for each model create `component-model-xxx` directory and package files (see https://github.com/elifesciences/elife-xpub/issues/1711)

- [ ] move `Manuscript` model into `component-model-manuscript`
- [ ] move `File` model into `component-model-file`
- [ ] move `Audit` model into `component-model-audit`
- [ ] move `Identity` model into `component-model-identity`
- [ ] move `SemanticExtraction` model into `component-model-semanticExtraction`
- [ ] move `Team` model into `component-model-team`
- [ ] move `User` model into `component-model-user`

- [ ] hook up newly moved code to the app and make sure there are no remaining files in the wider codebase relating to this.

__Are any model related tests left over in the wider code base after? How will we deal with that?__
