### ISSUE TITLE
Epic: The Grand Refactor - Round 2

### ISSUE THREAD

**Issue by hem-brahmbhatt** [elifesciences/elife-xpub#1723]
# The Grand Refactor

## Architectural Decision

https://github.com/elifesciences/elife-xpub/blob/develop/docs/adr/0005-hindawi-pattern.md

## Coding standards to follow

* Follow the directory structure laid out below. A component can include client, config, server, and test (browser and functional) folders.
* Components should have a single responsibility
* Models are injected making testing easier
* Model components should have resolvers for the respective graphql API queries/mutations
* components can use other components functionality - eventually this dependant functionality needs to live inside a shared space such as PubSweet so do this sparingly!
* ensure all new code has tests written for it

## Directory structure

[The full directory structure can be found here](https://github.com/elifesciences/elife-xpub/blob/develop/docs/adr/0005-hindawi-pattern.md#overview-of-suggested-architecture-pattern)

## Issues to create
- [ ] rename tests to unit or functional (should make it easier to do testing as part of following issues)
- [ ] use dependency injection and the strategy pattern for use-cases
- [ ] remove logic out of resolvers into use-cases
- [ ] __break dependencies between components/domains__
    - dependencies first need to be identified
    - depends on if there are any dependencies
