### ISSUE TITLE
Elife UI Components: move ui & global components to elife-ui-component

### ISSUE THREAD

**Issue by Cooryd** [elifesciences/elife-xpub#1735]
## Background
As part of #1705 we are moving code into package components. Once all of the models and bound contexts have been moved we will likely still have some left over client side shared components most likely in the `/ui` and `/components/global` directories. These should be shared presentational components such as layout wrappers and styled buttons ect. These shared components should be moved into their own `/packages` component called `component-elife-ui`. Once this is done, we can get rid of the `ui` and `global` alias that is being used as well as the jest and webpack config set for them.

## Tasks 

- [x] move code into component directory
- [x] change all import paths to use the new `@elifesciences/component-elife-ui` package
- [x] remove references to `ui` and `global` alias from config files
