### ISSUE TITLE
Move models into their own packages from component-model.

### ISSUE THREAD

**Issue by will-byrne** [elifesciences/elife-xpub#1786]
:warning: This issue is an epic that we use to create sub tickets for all models. Please see the related issues for each model below.

## Background

As part of #1705 we plan to phase the refactoring of the app code. Round 1 involves moving the code into a `component-xxxx` directory structure and should not require the changing of much code. This issue relates to moving / grouping the model components

## Tasks

- [x] for each model create `component-model-xxx` directory and package files (see https://github.com/elifesciences/elife-xpub/issues/1711)

- [x] move `File` to `component-model-file` see #1791 
- [x] move `Manuscript` to `component-model-manuscript` see #1789 
- [x] move `AuditLog` model into `component-model-audit-log` see #1799 
- [x] move `Identity` model into `component-model-identity` see #1805 
- [x] move `SemanticExtraction` model into `component-model-semanticExtraction` see #1793 
- [x] move `Team` model into `component-model-team` see #1800 
- [ ] move `User` model into `component-model-user` see #1801
- [ ] hook up newly moved code to the app and make sure there are no remaining files in the wider codebase relating to this.
