### ISSUE TITLE
Move health, cleanup and routes from xpub-server into elife app component

### ISSUE THREAD

**Issue by erezmus** [elifesciences/elife-xpub#1849]
## Subtasks
In xpub-server component
- [ ] Move health.js to component-elife-app/server/health.js
- [ ] Move cleanup.js to component-elife-app/server/cleanup.js
- [ ] Move cleanup.test.js to component-elife-app/server/cleanup.test.js
- [ ] Move routes inside the routes.js file into component-elife-app/server/routes/index.js
- [ ] Move routes.test.js to component-elife-app/server/routes/index.test.js
- [ ] Rewire imports as needed
