### ISSUE TITLE
Investigate and choose our security model

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1865]
## Requirements
The chosen model and implementation must be able to fulfil the following requirements:
- There must be a mechanism to give the user a short-lived (TBD) ability for a user, to perform an authorized task on a specified object.
- This mechanism should be able to be sent over email (to provide the email-bridge functionality #196)
- This mechanism should also be used when implementing anything like "God Mode"

## Subtasks
- [ ] Talk with others / read code (Hindawi / Thinslices) to see where their solution / thinking is.
- [ ] Research options - and produce a short summary.
- [ ] Share with the wider PubSweet community and get some feedback.
- [ ] Choose the most appropriate that can be implemented.

## Assumptions and notes
- Initial thoughts are to use https://en.wikipedia.org/wiki/Capability-based_security
- One outstanding question is should we have a combination of the above and Role-based security? We need to be clear on what whether implementing capability-based security is overkill? So many questions! 

/cc @hdrury1 / @BlueReZZ
