### ISSUE TITLE
Archived Editors within the System

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1870]
## Subtasks
Talk to @nlisgo / Editorial about archived editors.
- [ ] Should archived editors be returned on the API? I would expect them to be marked as archived. It is strange that an API query is valid one day and invalid the next.
- [ ] Should a submission be allowed with an archived editor? Then this gets adjusted at QC time.
- [ ] Determine a solution that considers the system as a whole in relation to archived editors.

**Comment by hdrury1** [comment]
Following initial conversations, we have a plan of attack for the xPub side of this.

1) Short term: 
a) make sure the app doesn't break if a user has suggested an editor that is no longer present in the Journal API (#1923)
b) do not validate against the API after a user has made their suggestions (Editorial have agreed to use human judgement when the submission reaches eJP)

2) Long term:
a) consider caching the list of Editors, thereby decoupling the two systems
b) to be looked at again in the context of improving People Picker performance
c) as we look to move beyond eJP we will need a way of flagging editor suggestions that have been archived to Editorial staff

We should look to speak to @nlisgo about how archived editors are treated by Journal CMS
