### ISSUE TITLE
Test SubjectAreaDropdown component

### ISSUE THREAD

**Issue by jsms90** [elifesciences/elife-xpub#195]
Tests for SubjectAreaDropdown #42 (component easily reviewed from PR #182)

Product requirements for component behaviour:
- [x] When a user first visits the page, then no validation message is displayed
- [ ] Given that no input is typed & no option chosen, when the user leaves the field (blur), then validation message is shown, prompting user to choose at least 1 option
- [x] When a user focuses on the field, then a dropdown appears with full list of options
- [x] Given that no input has been typed, when a single letter is typed, then the dropdown list is filtered by first letter
- [x] Given that a single letter has been typed, when the 2nd letter is typed, then the dropdown is filtered further (by first 2 letters)
- [x] When an option is selected from dropdown -> tag appears & dropdown closes
- [x] When 2 options are selected -> displays success message
- [ ] When 2 options are selected -> disables the dropdown
- [ ] Given that 2 options are selected, when 1 option is deleted, then the dropdown is re-enabled

Product requirements outside scope of testing (because this functionality is encapsulated within `react-select` itself):
- List should be keyboard navigable
- Use return for selection
- Tag can be removed by clicking cross icon

**Comment by jsms90** [comment]
Simulating the selection of an option from the dropdown list has been a lot trickier than expected. As I understand it, this is largely the case because of the non-intuitive behaviour of enzyme.

You can see that this is somewhat common problem for people, based on the following issues:
- "[react-select simulate 'change' not working](https://github.com/airbnb/enzyme/issues/400)" (enzyme's repo)
- "[Simulate 'change' doesn't work for select](https://github.com/JedWatson/react-select/issues/1357)" (react-select repo)
- "[Help with using react-select and adding test](https://github.com/JedWatson/react-select/issues/1523)" (react-select repo)
- "[Testing react select component](https://stackoverflow.com/questions/41991077/testing-react-select-component)" (Stack Overflow question)

But despite the titles of these issues, the problem does not seem to originate with `react-select`. Many issues have been raised in enzyme that point to similar problems for people who are not using react-select.

It seems as though the crux of the issue is that the `.simulate` method does not behave quite as you might expect.

One prevalent answer to people's questions across the enzyme repo is the idea that calling `props` is better than using the `.simulate` method:
> [We get a lot of these 3rd party lib questions like this where simulating a prop "event" doesn't work.](https://github.com/airbnb/enzyme/issues/222#issuecomment-256717634)

After much trial and error & issue reading, [this answer](https://github.com/airbnb/enzyme/issues/400#issuecomment-270331222) seems to have provided an example whose steps worked for me. I'm not 100% sure that I understand exactly why/how this works, or whether there is a more elegant method, but I have provided detailed comments in the code, in order to try to explain.

If you are really curious to understand what is going on at each step, stick `console.log(wrapper.debug())` between each line of code in turn. Seeing the output change, based on the simulated behaviour is the surest way I can think of to wrap your head around this :+1:

**Comment by hdrury1** [comment]
Product requirements look good!

**Comment by jsms90** [comment]
Testing the final checkbox on the list isn't really a SubjectAreaDropdown-specific test.

Seems more like an integration between that component and the whole page & is no different from testing any of the other validation messages that we display. How we test validation may be worth a wider discussion.
