### ISSUE TITLE
Allow Feature Article submitters to not select a Major Subject Area

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#1973]
## Problem / Motivation
- WHO wants this? Features editor
- WHEN and WHERE do they want it? Within the submission wizard, if a submitter selects 'Features Article' as their article type
- WHAT do they want? The application should update its validation rules based on the article type selection
- WHY do they want this? Certain article types (and Features Articles in particular) require different information from the author. In many cases, a Features Article will not need a Major Subject Area to be selected, or any editors suggested. Currently, submitters are having difficulties completing the wizard as there is information that is required to fulfil validation rules but that doesn't make domain sense.

## Proposed solution
- We should aim to update the validation rules depending on which article type has been selected on the 'Details' step of the wizard

## Clarification needed and assumptions
- The final step validation should catch any errors thrown if, for example, a submitter changes article type partway through a submission

---

## Tasks
- [ ] Is is possible? Hack together a meca zip which can be imported into eJP
- [ ] Make required changes to the validation (no MSA)
- [ ] Make required changes to mecaExport for a Feature Article.

## Technical notes
- We could use this technology
- More notes or suggestions

**Comment by hdrury1** [comment]
```
Hannah
Got some data on Feature Articles for you
- there were 62 ISFA submissions in 2018; there were 25 in Jan/Feb/Mar this year
- of the last 30 Feature Articles we published, 19 had MSAs and 11 did not
- of the last 30 Feature Articles we published, I was the Senior Editor for all of them, and me/Stuart/Emma/Helga were the Reviewing Editor for 29!

Best
Peter
```

**Comment by chris-huggins** [comment]
I suggest we add `(optional)` to the label of the `Subject area(s)` input when `Feature article` is selected in the article type dropdown. 

And of course we show no validation error for 0 added subject areas, but we retain the validation/additional text when 2 subject area(s) are selected, assuming that we still retain the maximum 2 subject area selections for Feature articles.

**Comment by diversemix** [comment]
I would break this down into:

- Is is possible? Hack together a meca zip which can be imported into eJP
- Make required changes to the validation (no MSA) 
- Make required changes to mecaExport for a Feature Article.

**Comment by hdrury1** [comment]
I've changed the title of the ticket to reflect a limit in scope. The Features Editor feels product requirements would be met if we allowed a submitting author to complete an ISFA submission with no subject area selected.

This would involve updating validation rules if the Features Article filetype is selected, and feeding this back to the client. The Subject Area(s) field should be labelled as (Optional) in this event.

I have contacted eJP to determine if they would be willing to update their MECA importer's validation rules to allow this field to have a `NULL` value.

**Comment by hdrury1** [comment]
Update: eJP have been in touch to confirm they will make the coding change needed to update the validation rules (i.e. no longer require a value in this field).

We should be able to go ahead and make the necessary changes our side.

**Comment by hdrury1** [comment]
Blocked pending coding update by eJP

**Comment by chris-huggins** [comment]
@hdrury1 While this is blocked I'm re-thinking my suggestion for how we showing this as optional when features article type is selected.

I suggest we add an "Optional" label in the validation line to the subject area picker instead of the label.

Below:

![image](https://user-images.githubusercontent.com/41907215/57850912-1970af00-77d7-11e9-8e3b-ee3f02884e3c.png)

Part of label: 

![image](https://user-images.githubusercontent.com/41907215/57851647-09f26580-77d9-11e9-9e58-00c28a411dcf.png)


I think this is a pattern we're likely to need further down the line anyway, and having it below the input means less danger of making input labels wrap to two lines on narrow screens (320px min). 

The downside is it would be replaced by validation states, but I assume we wouldn't expect an error state on this input if it is optional for features articles. 

Currently we show this if 2 subject areas are selected:

![image](https://user-images.githubusercontent.com/41907215/57851442-80429800-77d8-11e9-84f7-586b79a3b4ce.png)

I've found the green text/state a bit weird and suggest we also change to use the same grey as the "optional" label instead.

What do you think?

**Comment by chugginselifesciences** [comment]
@hdrury1 I'm adding this as part of testing linking to roadmap tickets. Please ignore this and I'll delete shortly.

https://github.com/elifesciences/xPub-features-roadmap-test/issues/7

**Comment by hdrury1** [comment]
Chased Joel today regarding the validation change.

**Comment by hdrury1** [comment]
This is no longer blocked- the coding change has been implemented by eJP so their validation rules now do not expect this field to contain a value.
