### ISSUE TITLE
Implement eLife stying for PubSweet components

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#203]
**InVision Prototype:** https://invis.io/NZKXOQUV4P3#/302926984_vertical_Spacing

There are 5 pages to navigate through with comments from @NickDuf.

**List of PubSweet agreed variables that should be applied to the components (have not always been, but we should ensure they are whenever we use them):** https://gitlab.coko.foundation/pubsweet/design/blob/master/VARIABLES.md

**Icon SVGs to be used:**
[icons (1).zip](https://github.com/elifesciences/elife-xpub/files/2101727/icons.1.zip)

**Icons still to come:**

- Progress indicator tick
- Keywords cross

### Tasks
- [x] Move elife-theme from pubsweet repo to elife-xpub (this) repo #215 
- [x] Update elife-theme variables to match invision prototype #217 
- [x] Update atoms and molecules
  - [x] Button (including small and extra small variants) #218 
  - [x] Textfield #220 
  - [x] Textarea (in eLife-xpub) #219 
  - [x] Checkbox #221 
  - ~Radio #222~ - not in this epic
  - [x] Select menu #223
  - [x] Progress indicator / Steps #224 
  - [x] Multiselect drop-down (including keywords) (in elife-xpub) #225 
  - [x] Heading #226 
  - [x] File Upload #234 #135 
  - [x] Cover letter editor #235 
- [x] Create new components
  - ~Select Button #227~  - pending product requirements & people picker
  - [x] Notification ribbon #228 
  - [x] Show/hide panel #229
  - ~Paragraph (including small body text variant) #230~ - not in this epic

**Comment by tamlyn** [comment]
Initial list of tasks created with @dryhten https://docs.google.com/document/d/13-_3V5O-tgOlyzAGEClaOglAuA2rl4pV1AriHODUvqM/edit

**Comment by dryhten** [comment]
@hdrury1 I guess we will discuss these on Monday standup before I go ahead and create the relevant issues if that's fine with you

**Comment by dryhten** [comment]
Actually scratch that. Just realised that me & Jen will do some YLD onboarding stuff on Monday, so nobody's going to be around I guess.

**Comment by jsms90** [comment]
I've copied the list of tasks over from the google doc into the issue above, so that we can link tasks to issues more easily & generally have github as our single source of truth. Less tabs :heart_eyes: 

We've decided not using milestones as features :+1: Having `epic` issues seems like it's probably a better way of organising everything. As a PR for each sub issue is merged, the checkbox can be ticked. Hopefully this makes it easier for you to have an overview of our progress @hdrury1

**Comment by jsms90** [comment]
Thanks for the [new invision designs](https://projects.invisionapp.com/share/QBLHWKHJZHM ) @hdrury1 :heart_eyes: 

Based on these new designs, I think we need a few more issues.

Styling:
- [`ValidatedField` component](https://github.com/elifesciences/elife-xpub/blob/develop/app/components/ui/atoms/ValidatedField.js) - this encompasses the font family, font size & spacing of all labels + sub-component (e.g. TextField) + validation message
- overall page components (basically just spacing)  
4 separate issues?
  - author details page
  - file uploads page
  - manuscript metadata page
  - reviewer suggestions page

Feature issues:
- creation of new component in `molecules`: link/button generated child - see #229 
- creation of new component in `molecules`: CheckboxGeneratedChild - see #229 
- update co-submission CheckboxGeneratedChild to conform to [new product requirements & designs](https://invis.io/CQJPAJR56Y2#/299813833_staff-Step-1)

**Comment by jsms90** [comment]
The spacing on the `ValidatedField` component & between all components on the page didn't make it in, in time for the internal product/design demo.

So these (and all other tweaks to the components listed above) were pushed into the body of work post product/design demo & onto the list of things for the eLife demo #267
