### ISSUE TITLE
Investigate the extent to which we can generate code based on the GraphQL definitions

### ISSUE THREAD

**Issue by petereast** [elifesciences/elife-xpub#2077]
## Subtasks
- [ ] Investigate the flexibility of the `graphql-codegen` AST
- [ ] Investigate generating `io-ts` validation schemas
- [ ] Investigate generating graphql server calls
- [ ] Investigate generating other utilities? The scope is endless!!

## Assumptions and notes
We currently use a thing called `graphql-codegen` that supports custom code generating plugins. `[graphql-codegen plugin docs](https://graphql-code-generator.com/docs/custom-codegen/write-your-plugin)` - this is also something we could contribute back to open source if it's useful.
