### ISSUE TITLE
Update front-end to use the new suggestions object

### ISSUE THREAD

**Issue by petereast** [elifesciences/elife-xpub#2098]
## Subtasks
- [x] Update the Graphql query to get the suggestions entry of the Manuscript
```graphql
-# Something like this
...something extends Manuscript {
   ....
    submission {
        fieldName
        value
    }
}
```
- [x] Write the `suggestion` to the title field in the form (if there's nothing there already)
- [ ] Update the API Test to include the `suggestions` property (even if it's just an empty array) cc @petereast 

blocked by #2034
