### ISSUE TITLE
Move elife-theme from pubsweet repo to elife-xpub (this) repo

### ISSUE THREAD

**Issue by dryhten** [elifesciences/elife-xpub#215]
Currently the elife-theme is located on the pubsweet repo here https://gitlab.coko.foundation/pubsweet/pubsweet/tree/master/packages/elife-theme

It should be moved to this repo so we can change it faster. The best location for the theme is probably the client directory.

This issue encapsulates the following tasks

- [x] Do a PR with the elife-theme files to this repo https://github.com/elifesciences/elife-xpub/pull/216
- [x] Do a MR on pubsweet removing the elife-theme files [!278](https://gitlab.coko.foundation/pubsweet/pubsweet/merge_requests/278)
- [x] Make sure we have the rights to publish new versions of the theme to the npm registry
- [x] PR to change the links with this repo to point to the new npm package location (https://www.npmjs.com/package/@elifesciences/elife-theme) #232 
~~Wait for PRs & MR to get merged~~

**Comment by jsms90** [comment]
I've updated the top comment to reflect the fact that we have a 2nd PR open against this issue. Once this is merged, all the necessary changes will have been made for elife-xpub :+1: 

But this ticket will not be considered 'done' until the MR to pubsweet has been merged - so it's 'blocked' until Coko merges.

**Comment by hdrury1** [comment]
Closing down this issue- work on our end is done.
