### ISSUE TITLE
Update elife-theme variables

### ISSUE THREAD

**Issue by dryhten** [elifesciences/elife-xpub#217]
Someone needs to check the new variables in the [styleguide](https://projects.invisionapp.com/share/NZKXOQUV4P3#/screens/302926979) and make sure that

- [x] We have all the required variables: all the variables mentioned in the styleguide are present in the theme file (`index.js`)
- [x] They have the right values: this goes hand-in-hand with the one above, just make sure all the variables have the right value from the styleguide
- [x] We have at least all the variables from [VARIABLES.md](https://gitlab.coko.foundation/pubsweet/design/blob/master/VARIABLES.md). If something is missing it should be added/discussed.
- [x] Discuss how to refer to vertical spacing sizes (XXS, XS, S, M, L, XL, XXL), and if we really need to: there are no variables in the theme for this; we can add variables (`sizeXXS`, `sizeXS` etc) or just use `gridUnit` instead (e.g. `gridUnit * 2` for XS); if future designs will use these labels (XXS, XS etc) it makes sure to define the matching variables
- [x] Decide what to do about `gridUnit`: since we are using PubSweet components that are designed with a gridUnit in mind of 24px, when we apply the elife-theme to them with a gridUnit of 6px, they will all get smaller which is not what we want. Possible solutions: either convince the PubSweet guys to change `gridUnit` to 6px like us and redesign their components or we could wrap each component we use from PubSweet and apply some width/height transformation (e.g. multiply by 4, which might change).

**Comment by jsms90** [comment]
> Decide what to do about gridUnit: since we are using PubSweet components that are designed with a gridUnit in mind of 24px, when we apply the elife-theme to them with a gridUnit of 6px, they will all get smaller which is not what we want. Possible solutions: either convince the PubSweet guys to change gridUnit to 6px like us and redesign their components or we could wrap each component we use from PubSweet and apply some width/height transformation (e.g. multiply by 4, which might change).

@dryhten see the invision docs where @tamlyn asked @NickDuf about this. Apparently pubsweet are changing gridUnit to 24px

**Comment by jsms90** [comment]
>  Discuss how to refer to vertical spacing sizes (XXS, XS, S, M, L, XL, XXL), and if we really need to: there are no variables in the theme for this; we can add variables (sizeXXS, sizeXS etc) or just use gridUnit instead (e.g. gridUnit * 2 for XS); if future designs will use these labels (XXS, XS etc) it makes sure to define the matching variables

Seeing the word 'size' on its own could refer to anything. Size of what?

I would suggest something like:
- verticalGridSpacing1
- verticalGridSpacing2
- verticalGridSpacing3
- verticalGridSpacing4
- verticalGridSpacing5
- verticalGridSpacing6
- verticalGridSpacing7

where 1 is the largest (follow the pattern used for headings).

Using sizes like XS & XL lock you in to the number of sizes you can use & force you to consider the middle value (M) to be your "default" point of reference and then go outwards. This is a nightmare for extensibility.

For example, if you wanted to add an 8th size that was in between S and XS (18px), what would you call it?

Because of the naming convention, you would probably add a new size on the end, called XXXS, and shunt all of the existing sizes down one:
- S - stays as 24px
- XS - 12px becomes 18px
- XXS - 6px becomes 12px
- XXXS becomes 6px

This means changing every component that uses XXS to use XXXS & every component that uses XS to use XXS. All because of a naming convention.

What do you guys think?

**Comment by hdrury1** [comment]
Thanks @jsms90! Looking at your cross-referencing:

colorAttention is an eLife variable and not one we use for xPub (we use colorError). Likewise colorTextDividers and colorTextUIBackgroundHue. Note this PDF was created as a reference for the internal eLife tech team too, hence the different variables. Anything preceeded with 'e:' we can ignore, we are only interested in those preceeded by 'ps:'.

I'm happy to add the fontLineHeight values if we need them. Note these variables currently don't exist in PubSweet so we should run them by Yannis. Similarly verticalGridSpacing.

I've removed subGridUnit because we don't use it, but would make sense to keep I guess in case we ever do.

**Comment by jsms90** [comment]
Ahhhh!!! So the invision doc is making a link between the pubsweet names (and therefore elife-xpub) & the names you guys use in other eLife projects. Gotcha! Thanks :smile:

**Comment by jsms90** [comment]
Is talking to Yannis about design variables something that you or @NickDuf are doing? Shall we put this issue in `blocked` until there has been an agreement between pubsweet & eLife designers?

Or shall we just pop these variables into our theme to get this issue completed & feed back to Coko separately?

**Comment by hdrury1** [comment]
I'm going to go ahead and make the requested changes, and we can feed back to Coko after the fact.

**Comment by dryhten** [comment]
@jsms90 regarding vertical sizes, if the design team is using those labels to measure margins and paddings (and they did in the current version of the styleguide) then it would make sense to me to define them. What can happen is that some day maybe they want to have `XS` to be `20px` instead of `12px`, then we would have to change all the components that have an `XS` padding. This seems more likely to happen than the design team coming up with completely new labels. If there is some special case of vertical size that doesn't fit there, we can always use a hardcoded number of gridUnits for it.

**Comment by hdrury1** [comment]
The t-shirt sizing is just an internal method @NickDuf uses and as far as I can tell the only instance of it right now is in the styleguide. If verticalGridSpacing is easier for you to understand then that's fine.

**Comment by hdrury1** [comment]
FYI the way this works for the eLife website is

`$blg-space-extra-small-in-px: 12;
$blg-space-small-in-px: $blg-space-extra-small-in-px * 2;
$blg-space-smallish-in-px: $blg-space-small-in-px * 1.5;
$blg-space-medium-in-px: $blg-space-small-in-px * 2;
$blg-space-large-in-px: $blg-space-small-in-px * 3;
$blg-space-extra-large-in-px: $blg-space-small-in-px * 5;`

**Comment by hdrury1** [comment]
So maybe we define the smallest unit (gridUnit) and everything else is just that multiplied.

**Comment by jsms90** [comment]
Hmm looking at the "Spacing examples" section in invision, it seems like "vertical spacing" is achieved in one of multiple ways:
- padding
- margin
- a combination of both

In the situations where a combination of margin & padding are achieving "vertical spacing" of 24px, having a single variable in the theme won't help us.

But there do seem to be situations where it would be purely padding e.g. ][padding on the Button component](https://gitlab.coko.foundation/pubsweet/pubsweet/blob/master/packages/ui/src/atoms/Button.js#L37)?
![image](https://user-images.githubusercontent.com/15656538/41667787-bddd5fd8-74a5-11e8-9495-80d6049819c5.png)

The way this is currently being achieved is through calculations against `gridUnit` - see [the issue where this has been discussed before](https://gitlab.coko.foundation/pubsweet/design/issues/10)

I don't think we need these variables after all?

**Comment by jsms90** [comment]
Oh yes, stupid me. It even says directly under "Vertical spacing":
Xxs: 6px
gridUnit

Yes, we definitely don't need these extra variables. Sorry @hdrury1

**Comment by jsms90** [comment]
@hdrury1 I've raised issues or commented on existing issues in the pubsweet design repo, to deal with the discrepencies between pubsweet & our new eLife theme:
- [clarify use of `boxShadow` vs `dropShadow`](https://gitlab.coko.foundation/pubsweet/design/issues/29)
- [we're using separate lineHeights for each heading](https://gitlab.coko.foundation/pubsweet/design/issues/30)
- we've [removed `subGridUnit`](https://gitlab.coko.foundation/pubsweet/design/issues/24) and are [specifying multiple "gridUnit"s](https://gitlab.coko.foundation/pubsweet/design/issues/31) instead of using a [different padding variable](https://gitlab.coko.foundation/pubsweet/design/issues/10)
- our designs call for [a `warningColor` variable](https://gitlab.coko.foundation/pubsweet/design/issues/22#note_23069)

**Comment by hdrury1** [comment]
@jsms90 Correct, we'll be using 6px. As far as I can see, VARIABLES.md uses dropShadow, so presumably this will be updated throughout the PubSweet repo at some point?

In any case, I agree this can be closed. Thanks all!

**Comment by jsms90** [comment]
@hdrury1 See Julien's comment [on the design repo issue](https://gitlab.coko.foundation/pubsweet/design/issues/29):
> boxShadow would make more sense as it's tight to the css property name

All of the themes use `boxShadow`, despite the documentation erroneously saying `dropShadow`. I think this is just a mistake and using the same name as everyone else & the same name as CSS itself would probably be better
