### ISSUE TITLE
Make tools/api-tests/src more consistent with the rest of the project

### ISSUE THREAD

**Issue by petereast** [elifesciences/elife-xpub#2191]
The API tests have been developed in isolation from the rest of the project, we need to stop developing them in isolation before it's too late!

## Subtasks
- [ ] Use the global prettier config
- [ ] Use the global eslint (well, tslint) config
- [ ] Include the `api-tests` in the precommit hooks
- [ ] Bring the docs up to spec

### Note
Just to be clear - this is not a unit of work to absorb `api-tests` into the `packages` directory, it is to make the code more consistent with the rest of the project, without integrating it into the project.
