### ISSUE TITLE
Quarantine old database unit tests

### ISSUE THREAD

**Issue by will-byrne** [elifesciences/elife-xpub#2215]
As per the discussion last week we need to move the existing integration tests into the api-tests. This is a 2 phase operation and to ensure we maintain our current test coverage we need to re-write the tests as unit tests after making a quarantined copy to convert to an api-test.

## Subtasks
- [ ] identify unit tests that connect to the database
- [ ] copy to `${testName}.quarantine.js`
- [ ] rewrite existing tests as unit test with mocks
