### ISSUE TITLE
Move browser tests to Acceptance tests

### ISSUE THREAD

**Issue by will-byrne** [elifesciences/elife-xpub#2218]
We need to convert our existing browser tests to acceptance tests.
## Subtasks
- [ ] Move the existing browser tests to a new `AcceptanceTests` folder
- [ ] Rename browser tests from `${testName}.browser.js` to `${testName}.acceptance.js`
- [ ] Alter jenkins file to separate them from integration tests.
