### ISSUE TITLE
Update Multiselect Menu atom to conform to the styleguide

### ISSUE THREAD

**Issue by dryhten** [elifesciences/elife-xpub#225]
The Multiselect Menu molecule should look like the one in the [styleguide](https://projects.invisionapp.com/share/NZKXOQUV4P3#/screens/302926985) (Select Menu with Keywords).

![image](https://user-images.githubusercontent.com/15656538/41714701-25450100-7549-11e8-84bb-ff4dd6fd4306.png)

![image](https://user-images.githubusercontent.com/15656538/41664524-d50acad6-749d-11e8-9b05-1fa120101e1e.png)

![image](https://user-images.githubusercontent.com/15656538/41664490-c4d074ae-749d-11e8-944b-f09f99d20ec4.png)

### Tasks
Sub components within react-select:
- [x] 1. Update styling of input field
  - [x] border changes based on validation status
  - [x] font family, font colour & other border variables
  - [x] spacing - padding/margin
- [x] 2. Update styling of menu options
  - [x] font colour on hover
  - [x] background colour on hover
  - [x] spacing
- [x] 3. Update styling of tags (aka keywords)
  - [x] font size
  - [x] font colour
  - [x] overwrite `react-select` hover behaviour
  - [x] spacing

---

Right now we don't have any Multiselect Menu component. We have a [Subject Area Dropdown](https://github.com/elifesciences/elife-xpub/blob/develop/app/components/submission/ManuscriptMetadata/SubjectAreaDropdown.js)  which should probably get more modular and be moved to `molecules`.

**Comment by jsms90** [comment]
@dryhten the Subject Area Dropdown component is a specific version of the generic multiselect dropdown that has already been created in the `react-select` library. I disagree that we should create a generic multiselect menu component in `molecules` as an extra middle step.

We currently only have one implementation of a multiselect menu in our application. Until we have more multiselect dropdowns in our app, I'm not sure that a middle abstraction is useful/necessary.

With that in mind, I'm adding "Tasks" to the top comment, with the view to simply styling the SubjectAreaDropdown component as per invision.

**Comment by jsms90** [comment]
1. First step - make sure I'm using the custom styles object in `react-select` correctly.

The sub-component that needs the custom styles is called `Control`, so I've added `borderColor` like this:
```
this.customReactSelectStyles = {
      multiValue: (base, state) => ({
        ...base,
        backgroundColor: this.props.theme.colorPrimary,
      }),
      control: (base, state) => ({
        ...base,
        borderColor: 'green'
      }),
    }
```
It works. The border is green, except on hover & on focus.

Went digging in the source code, to see what else from the base styles I needed to replace - [this code here](https://github.com/JedWatson/react-select/blob/v2/src/components/Control.js#L48-L50)

So:
```
this.customReactSelectStyles = {
      multiValue: (base, state) => ({
        ...base,
        backgroundColor: this.props.theme.colorPrimary,
      }),
      control: (base, { isDisabled, isFocused }) => ({
        ...base,
        borderColor: isFocused ? 'none' : 'green',
        '&:hover': {
          borderColor: isFocused ? 'none' : 'green',
        },
      }),
    }
```

**Hard coding this works :+1: - so potential issue no.1 isn't it.**

**Comment by jsms90** [comment]
Forgot to say - the issue above was about using styled component & emotion differently
- needed to pass in `this.props` rather than just `props` to the borderColor function
- was also defining the borderColor function outside of the stateful component itself (but in the same file)
