### ISSUE TITLE
Update pages to conform with hi-fi wireframes

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#267]
**Product requirements/Acceptance criteria:**

Functional:

Content on the pages of the submission wizard should be centred in relation to the page.
Each component should be left-aligned in relation to each other, with the exception of the progess indicator which should be centred in relation to the other components on the page.
Design should remain responsive for mobile screens.

**Relevant links to design(s):**

See the hi-fi wireframes for reference [here](https://invis.io/PUM5HBTGY6Z#/304489193_wizard-Screen-1).

**Tasks:**
- [x] Remove drop shadow from subject area dropdown #288 
- [x] update progress indicator styling #224 
- [x] apply consistent spacing to Next and Back buttons #316 
- [x] make layout responsive #321 
- [x] fix the rest of the spacing between components #324 
- [x] remove success validation #303 
- [x] show progress animation for manuscript upload #135 
- [x] report upload progress for manuscript #313 
- [ ] use `react-select` for the "Article type" dropdown instead of pubsweet's `Menu` component #326   
(bug reports in issue #308)
- [ ] fix `SubjectAreaDropdown`'s internal spacing #327 
- [x] change co-submission box - now only 1 input field + `Action` link, which should generate more input fields #328 
- [ ] Scroll up to first validation error on clicking next #330 
- [x] Update 'Considered previously' box (label should be 'Article title')
- [x] Add 'Tools and Resources' and 'Short Repot' options to article type dropdown
- [x] Limit number of exluded reviewing editors to 2
- [ ] cover letter editor - add hover and selected states to formatting buttons #462 
- [ ] Use only bottom margins #341

**Comment by jsms90** [comment]
Of the 3 functional requirements, the first 2 are already satisfied & @tamlyn is working on the responsiveness in another issue.

So if there are no objections, I might turn this into another "meta issue" for @hdrury1 to keep track of all the changes that need making to the UI before we demo?

**Comment by jsms90** [comment]
### Accessibility additions from @davidcmoulton 

#### All pages
- Need to add `h1`s to each page & visually hide them - see eLife's pattern used elsewhere: https://github.com/elifesciences/pattern-library/blob/develop/assets/sass/_mixins.scss#L140

### File upload page
- Each input within the file upload page needs a heading (h3). Could be visually hidden
- Orcid ID on top right needs an aria-label ("you are logged in with Orcid ID")
- Progress indicator accessibility - all divs and spans. If it's got a visually hidden h1, maybe aria hide the progress indicator. Make it an ordered list with an aria label attribute that describes what the list is & its context (e.g. completed step, current step, future step)
- File upload itself - no announcement of state change. Should be an aria live region

### Metadata page
- Subject Area Dropdown is announcing the number of dropdown elements that are available, as soon as you enter the page
- Announces the down arrow icon - should either be a background image or hidden
- Subject Area Dropdown doesn't allow you to move down the list with screen reader controls i.e. forward and back keys (tab and down keys are fine)
- Focus drops of the page if/when 2 items are chosen from Subject Area Dropdown
- "Success message" should have ID & field should have aria `described-by` with the same value

### Suggestions page
- When you click 'exclude' or 'suggest more', focus needs to go to the new items that have been added to a page
- 'suggest' and 'exclude' actions should be on separate lines
- 'X' icon within callout box should be a button

How much of this needs to go into this meta issue & therefore be done before the demo, is still to be decided.

**Comment by hdrury1** [comment]
Deprioritising while we work on the people picker.

**Comment by hdrury1** [comment]
Closing this off. Remaining tickets are in the Backlog.
