### ISSUE TITLE
Implement People Picker modal for initial submission wizard

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#345]
**User Story:**

_As a submitter I want to be able to suggest the editors best placed to assess my work, as well as those who should be excluded from the process in order to ensure I receive a fair and appropriate review._

**Tasks to complete:**

_Refactor_
- [x] #367 Improve folder structure for components/pages

_Person pods_
- [x] #227 Create a "Person pod" component
- [x] #404 Keep space for missing items in person pod
- [x] #403 Handle editors with no institution
- [x] #397 PersonPod Icons should darken on hover

_Modal screen_
- [x] #371 Create Tag component (atom)
- [x] #346 Create people picker modal component
- ~#353 Create some test people data for the application~
- [x] #383 Create generic modal container
- [x] #356 Create cancel/add bar component
- [x] #354 Implement ability to select person(s) within the picker modal  
- [x] #355 Impose a limit on number of possible selections

_Assemble pod & modal on reviewer suggestions page_
- [x] #351 Connect people picker modal to app  
- [x] #342 Update the panel for excluding editors to match new wireframes  
- [x] #343 Add ability to delete selected person(s)
- [x] #405 Editor suggestions validation
- [x] #402 Hook up people picker modal to browser navigation

_Populate picker with data_
- [x] #401 Fetch editor data from eLife API

_Bugs_
- [x] #455 Fix institution is null warning on People Picker Modal

**Comment by diversemix** [comment]
@hdrury1 Closed this out ... we're thinking it best if you close epics in the future, just to confirm all is done?
