### ISSUE TITLE
Add search functionality to people picker

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#378]
**User Story:**

_As a submitter I want to be able to filter the total number of people in the picker as I see fit, so I have a smaller number to select from._

**Tasks to complete**

Original designs/functionality:
- [x] #347 Create search box
- [x] #349 Search box offers suggestions
- [x] #439 Add SearchBox to PeoplePickerModal
- [x] #454 Move Search Box state from People Picker Modal to People Picker
- [x] #457 Add contextual titles to People Picker modal
- [x] #467 Sort list of People Pods in People Picker alphabetically by default
- [x] #443 Improve search/filtering functionality for the People Picker
- [x] #350 Populate people picker according to selection context
- [x] #437 Use styled components instead of CSS modules to style the SearchBox
- [x] #470 Write tests for Search Box
- [x] #527 Write tests for PeoplePicker (integration of the search functionality)

Update to new designs/functionality:
- [x] #547 Create new component - button with icon inside
- [x] #438 Turn search icon into search button
- [x] #540 Add option to clear search box and update component UI
- [x] #587 Write tests for Search Box icons

**Comment by dryhten** [comment]
Updated the list of tasks with what I think makes sense.

**Comment by dryhten** [comment]
@hdrury1 I have a question and I don't know in which issue to ask. It seems that we can't get the e-mail address for editors from the eLife API. Is there another API we can use for that? In that case the designs here cannot be done with 100% accuracy

https://projects.invisionapp.com/share/FUMJS349R2E#/screens/305823534_staff-Picker-Reviewers-Search

I could show the name but not the e-mail.

**Comment by hdrury1** [comment]
@dryhten This is part of a bigger issue which requires plumbing data from eJP. Luckily, for the submission wizard we don't need to display a list of reviewers in the PP so we can park this for now pending further investigation.

**Comment by hdrury1** [comment]
Updated original task list to deprioritise nice-to-have functionality.
