### ISSUE TITLE
Create subject area control molecule (wireframe 006)

### ISSUE THREAD

**Issue by g-sam** [elifesciences/elife-xpub#42]
Latest wireframes:
![image](https://user-images.githubusercontent.com/15656538/40132256-3be78b34-5934-11e8-8738-73c791371746.png)

[requirements here](https://github.com/elifesciences/elife-xpub/issues/42#issuecomment-387726579)

---

Old version:
![multiple-choice-menu](https://user-images.githubusercontent.com/15656538/39183884-6a3f910c-47b9-11e8-8da0-0bf274b61399.png)

### Tasks
+ [ ] Build UI molecule
+ [ ] Request list of subject areas from eLife API on page load

**Comment by tamlyn** [comment]
Does it make sense to park this until the mega-people-picker component is better specified? We can use the existing [Tags](https://ui-staging-zpqsip.gateway.ps.semioticsquares.com/#!/Tags) atom in the interim.

**Comment by NickDuffield** [comment]
I think it might. The subject picker will differ from the people picker. I would avoid using the tags for now though as I am unsure if this is the correct component for this use.

**Comment by g-sam** [comment]
This is now confirmed as a dropdown with checkboxes

**Comment by jsms90** [comment]
Design TBC - see https://github.com/elifesciences/elife-xpub/issues/45#issuecomment-383931608

**Comment by NickDuf** [comment]
**Example A:**  Default text area input
**Example B:** On focus scrollable full subject area list is displayed. Display 6 items before scroll. List closes on item selection or blur. List should be keyboard navigable using return for selection.
**Example C:** List is refined by entering letters. First letter of subject is used for matching and is further refined by following letters.
**Example D:** Single keyword input can be removed by clicking cross icon.
**Example E:** Two inputs displays validation message and disables the menu until an item if removed.

**Reference:** http://textextjs.com/manual/examples/autocomplete-with-tags.html
Some issues with the above jQuery example. Selecting items from the list using touch doesn't work properly. Scrolling can be problematic.

[subject-keyword-picker.zip](https://github.com/elifesciences/elife-xpub/files/1987828/subject-keyword-picker.zip)

**Comment by jsms90** [comment]
Pre-existing components:
- https://github.com/bharani91/react-select-popover
- https://github.com/instructure-react/react-tokeninput
- https://github.com/reactjs/react-autocomplete
- https://github.com/i-like-robots/react-tags

**Comment by jsms90** [comment]
| Features | React tags | React select |
| --- | --- | --- |
| Full list shown on focus | No | No |
| Scroll-able dropdown | No | No |
| List closes on item selection or blur | Yes | No |
| List should be keyboard navigable | Yes | Yes |
| Limit number of items selected | No | No |

**Comment by jsms90** [comment]
Current view:
![subject-area-dropdown](https://user-images.githubusercontent.com/15656538/40772603-56d679de-64b8-11e8-8273-326b7b49f265.png)

Todo:
- [ ] Limit user to 2 choices
- [ ] Demonstrate this limit to users visually i.e. add "No more than 2..." message
- [ ] Pull dropdown contents from eLife API (currently hard coded)
- [ ] Styling
    - [ ] display 6 suggestions in the dropdown list before scroll, rather than 4
    - [ ] move 'x' inside tags to right hand side
    - [ ] default colour for tags shoudl come from eLife theme
- [ ] All other styling (e.g. layout such as margins) to wait until @NickDuf returns

Further questions for @NickDuf:
- How do you feel about the dropdown arrow that's present in the `react-select` component? It's not in our latest high-def designs but was in the old mockups & it seems quite helpful from a UX perspective. What do you think?
- Would you prefer it if I removed the 'x' on the right-hand side which clears all the tags from the input field? (also not in designs)  
It's a nice little touch, but maybe not so necessary since we're already limiting users to only 2 entries & they do have 'x' on each tag

Further questions for @hdrury1:
- Perhaps it would be better to filter the dropdown list based on more than just the first letter(s)?
> > Example C: List is refined by entering letters. First letter of subject is used for matching and is further refined by following letters.

For example, if a user types "b", "i", "o", should they not see a list which contains:
    - Cell **bio**logy
    - Structural **bio**logy...

rather than limiting the list to items which _start_ with "bio" as the first 3 letters?
Especially considering the fact that we're showing users the dropdown as soon as they focus on the field, because the assumption is that users may not know the names of the available subject areas. What do you reckon?

**Comment by jsms90** [comment]
@hdrury1 Makes perfect sense. :+1:

Yes, if you type in "b", you see all instances where b appears anywhere in the word. You can play with it in the [demo](https://jedwatson.github.io/react-select/) if you're curious. Make sure you go down to the "multiselect" one.

I was wondering whether we should even go a little further and add the bold, as I did above?
    - Cell biology
    - Structural biology...

Kind of like [this component](http://i-like-robots.github.io/react-tags/) has bold & undeline on the letters you've typed.
(Note: that component requires you to type 2+ letters and only matches on the beginning of the word)

**Comment by hdrury1** [comment]
- Thumbs up to adding the bold styling

- Would it be out of the question to squish the two options together? What I mean is, typing one letter only matches based on the beginning of the word, typing more than one matches based on the whole word. So:

Typing "c" is going to give me 'Cancer Biology', 'Cell Biology', 'Computational and Systems Biology' etc.

Typing "ce" is going to give me 'Cell Biology' but also 'Developmental Biology and Stem Cells'

**Comment by jsms90** [comment]
Hmm theoretically possible to switch between 2 methods of filtering, but I wouldn't advise it from a UX point of view. I'm not sure that it would be particularly intuitive for a user. I would expect that typing more letters narrows down the search, not for 'Developmental Biology and Stem Cells' to be missing when I type 1 letter and then appear once I've typed 2. :thinking:

**Comment by hdrury1** [comment]
Okay, for a first pass let's follow @NickDuf's original designs and filter by first letter, with each subsequent letter narrowing down the search. We can get user feedback once it's in front of them and update accordingly based on that.

**Comment by hdrury1** [comment]
@jsms90 In order to get this off your desk, let's hard-code the subject areas for now (see GraphQL Schema).

**Comment by hdrury1** [comment]
Subject areas:

Biochemistry and Chemical Biology
Cancer Biology
Cell Biology
Chromosomes and Gene Expression
Computational and Systems Biology
Developmental Biology and Stem Cells
Ecology
Epidemiology and Global Health
Evolutionary Biology
Genetics and Genomics
Human Biology and Medicine
Immunology and Inflammation
Microbiology and Infectious Disease
Neuroscience
Physics of Living Systems
Plant Biology
Structural Biology and Molecular Biophysics
