### ISSUE TITLE
Store the Data in a database

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#425]
List:
- [x] #421 Merge the GraphQL schema
- [x] #424 Update the Application to use the schema
- [x] #436 Use teams on Manuscript
- [x] #423 Create SQL schema from GraphQL schema
- [x] #422 Implement ADR-004
- [x] #473 Use individual tables instead of "entities"
