### ISSUE TITLE
Move icons into theme

### ISSUE THREAD

**Issue by jsms90** [elifesciences/elife-xpub#427]
Pubsweet's uses a library called `react-feather` for its icons - see [their Icon atom](https://gitlab.coko.foundation/pubsweet/pubsweet/blob/c5d218a716d2deab420b12143dcc11b7d20d06aa/packages/ui/src/atoms/Icon.js).

This component is used by specifying the name of the icon you want to use from `react-feather` as a string, which is a child of the Icon component. e.g.
```
<Icon>select_circle</Icon>
```

Because eLife uses its own custom icons, rather than the `react-feather` library, we have had to create [our own icon atom](https://github.com/elifesciences/elife-xpub/blob/develop/app/components/ui/atoms/Icon.js). This component is used in the same way - the string inside `<Icon></Icon` refers to the name of a component that sits inside our [`icons` folder](https://github.com/elifesciences/elife-xpub/tree/develop/app/components/ui/atoms/icons).

When we want to override the default icons used by pubsweet in its other components (e.g. the tick icon inside the progress bar), we resort to [forcing in our SVGs in via background-image](https://github.com/elifesciences/elife-xpub/blob/develop/client/elife-theme/src/elements/ui/Steps.js#L52-L54).

Ideally, we would share all of this back to pubsweet & at the Pubsweet Meet, it was generally agreed that icons should be part of the theme :tada: 

#### Tasks
- [x] #429 add icons to the `elife-theme`
- [x] #464 use react-feather as default icon set & add concept of icon overrides to theme 
- [x] #428 change custom icons to Material icons
- [ ] #483 define a single methodology for creating and using custom icons
- [ ] https://gitlab.coko.foundation/pubsweet/pubsweet/issues/411 MR to pubsweet, so their icons come from the theme
- [ ] MR(s) to pubsweet to enable icons to be swappable (e.g. `Checkbox` & `Steps`)
