### ISSUE TITLE
refactor to prepare eLife codebase for icons moving to the theme

### ISSUE THREAD

**Issue by jsms90** [elifesciences/elife-xpub#428]
Currently, our icons specify their own sizes (e.g. height="1em" on the plus icon).
Then [the Icon component](https://github.com/elifesciences/elife-xpub/blob/develop/app/components/ui/atoms/Icon.js) adds sizing via CSS, which is based on grid units from the theme

But in reality, the same icon might be used in multiple places in the codebase, with different colours applied and different sizing, depending on the context. Therefore the responsibility for the sizing, colour, etc should lie with the parent component which _uses_ the icon, instead of the SVG itself or the Icon component that pulls it in from the folder/theme.

#### Tasks
- [ ] adjust all existing icons to conform to a new convention that makes them more easily themeable (e.g. size defaults to 100% of its container, SVG colour deafults to `currentColor`)
- [ ] tidy up our `Icon.js` component (e.g. remove the container wrapping the "SelectedIcon")
- [ ] adjust our components which make use of `Icon.js` - make these parent components responsible for an SVG's sizing, colour, etc (via CSS)

**Comment by jsms90** [comment]
### Background
The default icon set used by pubsweet is a library called `react-feather`. This library takes each SVG from [`feather-icons`](https://feathericons.com/) and converts it to a React component. Every one of these components is built in the same way - they take in a `color` prop, which defaults to `currentColor`, and a `size` prop, which defaults to `24` - [see just one example](https://github.com/carmelopullara/react-feather/blob/master/src/icons/activity.js). **The assumption that this library makes is that colour and size are context-specific**, so the parent _using_ the icon component should be responsible for setting these properties :+1:

In pubsweet, we have the concept of a single `Icon` component, which wraps any icon that you pass to it  & adds styles based on your theme. So if you write: `<Icon>plus</Icon`, the Icon component does the following:
1. looks for a `react-feather` icon named "plus"
2. wraps it in a container
3. applies styling to the SVG based on your theme

Oddly, the `Icon` approach goes against the assumption from `react-feather` that styling will be context-specific. Instead, `Icon` applies the same colour and size from your theme (e.g. `colorText`), regardless of the context in which the icon is used.

We already have one situation in which this doesn't work for us - the Cross icon is used in 2 places: a small white cross in `SelectedItem` & a larger grey cross in `CalloutBox`. I imagine, in future, there will be others

In fact, wrapping all our icons in an `Icon` component which is responsible for applying a single colour doesn't quite work either. For example, the Selected Tick icon has 2 colours inside it (i.e. it's more complex than the feather icons), so applying a single "color" to the whole icon doesn't make much sense.

### Current situation in our app
Currently, there is no consistency around how SVGs are created or used, or around how icons conform to the theme.

Importing:
- Some people have imported the `Icon` component & passed in our icons' names as a string, in the same way that we pubsweet does for its react-feather icons
- Others have imported the icon directly, without the `Icon`'s container + styling

Applying styles from the theme:
- **Completely hard coded values**: some icons [have size and/or colour hard-coded into them](https://github.com/elifesciences/elife-xpub/blob/develop/client/elife-theme/src/icons/Checkmark.js)
- **Color is applied by the icon but dynamic according to the theme** - some icons are wrapped in `withTheme` & [are themselves responsible for choosing a specific colour variable](https://github.com/elifesciences/elife-xpub/blob/develop/client/elife-theme/src/icons/Upload.js#L72) - this is similar to hard-coding would still need to be overriden by the parent, if the colour needed to change based on the context in which it was used
- **Size is applied by the parent** - in some places, we used to use the `Icon` component & pass in the `size` prop, so the `Icon` component was responsible for sizing based on the theme. In order to remove the `Icon` component from the codebase, these icons are now themselves responsible for applying the size based on the theme
- **All styles are applied by the parent** - [e.g. PersonPod](https://github.com/elifesciences/elife-xpub/blob/6d41ff69f67d7c0e6a9ec380028006040b7c5010/app/components/ui/atoms/PersonPod.js#L14-L17)

**Comment by jsms90** [comment]
Updating the top comment to reflect a discussion that happened on Slack last Friday - eLife wants to use Material icons wherever possible. So wherever the icons we have been given were not custom drawn, we should replace these with the actual Material SVGs & add them to the codebase next to the Apache license.

**Comment by jsms90** [comment]
Chris/@hdrury1 here's the "selected" state of the PersonPod from the invision designs: 
![image](https://user-images.githubusercontent.com/15656538/44087723-a59eaff6-9fb8-11e8-811b-9498ef219ecd.png)

Here's the implemented version, using Material icons:
![image](https://user-images.githubusercontent.com/15656538/44087814-e9f1528a-9fb8-11e8-8ec0-5b3cb022735f.png)

I'm guessing that this is an example of Nick going with a custom design over using Material icons. So, for now at least, I could leave the custom icon in there rather than using Material icons, so it looks the same as the designs?

But it's worth noting that:
- the way that our custom tick SVG has been created does not make it as simple as it perhaps should be to add styles (e.g. apply the correct colour)
- if we're using custom-made tick icons instead of Material's tick icons (in my opinion, ours do look much nicer :grin:), then perhaps all our tick icons should be drawn in a consistent way?

Here's the other custom tick that we have - the one used as "UploadSuccess":
![image](https://user-images.githubusercontent.com/15656538/44088274-742e378c-9fba-11e8-81f3-3562f51b5a08.png)

If you look at them side by side, you can see that the ticks aren't the same size.
![image](https://user-images.githubusercontent.com/15656538/44088428-f6923e12-9fba-11e8-8ef4-761aa72748be.png) 
![image](https://user-images.githubusercontent.com/15656538/44088497-320dfb70-9fbb-11e8-9454-01d310a2b663.png)

So if we're going to create our own custom icons, we should probably at least make them consistent with each other? If you look at the code, the way the two are made are also completely different, which makes the way that you need to access the internal elements different. Ideally we would draw these SVGs in the simplest way for us to add styling on top, perhaps even copying the same method that Material icons uses.

Anyway, this just gives you a bit of an idea about what discussion I feel we could be having with Chris. Again, for now we can continue using both custom ticks rather than Material icons, @hdrury1?

**Comment by hdrury1** [comment]
Yes, this is a discussion for Chris and not an immeadiate priority, so let's stick with the custom ones for now with the understanding they may be swapped out in the future.

**Comment by jsms90** [comment]
With respect to these:
> - adjust all non-Material icons to conform to a new convention that makes them more easily themeable
> - make parent components responsible for an SVG's styles (sizing, colour, etc) in a consistent way

I've made some adjustments along the way, but a wider conversation prob needs to be had with Chris before this can be finished.

Created a new issue & putting it in the backlog for now - #483
