### ISSUE TITLE
Add hover and selected states to cover letter buttons

### ISSUE THREAD

**Issue by jsms90** [elifesciences/elife-xpub#462]
Looks like we missed this, when we were making the list of tasks for conforming to high def designs

![image](https://user-images.githubusercontent.com/15656538/43902811-ed9ea664-9be2-11e8-8439-c1df788be785.png)

#### Tasks
- [ ] check whether custom styling is possible with `xpub-edit` and/or `prose-mirror`
- [ ] implement hover state styling
- [ ] implement selected state styling

Note: ensure this works regardless of the icon set which is used

**Comment by hdrury1** [comment]
Closing in favour of #1413
