### ISSUE TITLE
use react-feather as default icon set & add concept of icon overrides to theme

### ISSUE THREAD

**Issue by jsms90** [elifesciences/elife-xpub#464]
Ideally, we don't want to be importing a _specific_ icon directly from the theme - e.g. [in PersonPod](https://github.com/elifesciences/elife-xpub/blob/develop/app/components/ui/atoms/PersonPod.js#L8-L12):
```
import {
  PlusIcon,
  RubbishBinIcon,
  SelectedTickIcon,
} from '@elifesciences/elife-theme'
```

This couples a specific iconset to the components that are using it, which is what we want to get away from. Instead, we want the choice of icon to be dependent on which theme you use.

See the conversation in pubsweet from [this point in the issue](https://gitlab.coko.foundation/pubsweet/pubsweet/issues/411#note_25771) onwards.

### Tasks
- [x] remove direct exports of individual icons from the theme (e.g. `export { default as UploadIcon } from './icons/Upload'`) & export all icons instead (`export { icons }`)
- [x] add concept of icon overrides to theme - an `icons` object that maps names (e.g. "upload") to specific icons from your icon set (i.e. "arrow-up-circle`)
- [x] remove direct imports of individual icons within the components that use them (e.g. ``import { SelectedTickIcon } from '@elifesciences/elife-theme') & replace this with an `Icon` component that is responsible for fetching the right component
- [x] Icon component should default to react-feather, unless an override is specified in the theme
