### ISSUE TITLE
define a single methodology for creating and using custom icons & change exist custom icons to match

### ISSUE THREAD

**Issue by jsms90** [elifesciences/elife-xpub#483]
After changing most of our icons to use Material (#428), we only have the following custom icons left:
- `CheckCircle` - used in the PersonPod
- `FormatSubscript` & `FormatSuperscript` - used in the cover letter editor
- `Upload`, `UploadFailure`, `UploadSuccess` - used in the File Upload component

Each has different default sizing. Each has its colour and any alternative sizing applied in different ways. The upload icons in particular follow a very different method - applying styles to themselves.

### Default sizing
The SVGs were all made in a slightly different way. Unlike in react-feather or Material icons, the height, width, viewbox values are not standardised. Ideally, it might be nice to use the same standard: `viewbox="0 0 24 24"` & default to 24px for height and width?
- CheckCirlce - `viewBox="0 0 36 36"`
- FormatSubscript - `viewBox="-4 -4 24 24"`
- FormatSuperscript - `viewBox="-4 -2 24 24"`
- Uploads - `viewBox="0 0 52 52"`

Some have height and width defaults, some have them coming dynamically from the props, some have nothing written explicitly.

### Applying size & colour
The `react-feather` library (used in Pubsweet's default theme) wraps "feather" SVGs in a React component and passes `color` and `size` as props. Presumably the idea is for the parent component that uses it, to essentially configure how the icon looks in that particular context, using props. In my personal opinion, applying styles through a combination of props (via either JSX or attrs with styled-components) and CSS (styled-components) is not ideal.

So with the Material icons, I have left it up to the parent to use `styled-components` to apply colour and size, along with anything else (e.g. cursor=pointer).

This becomes more difficult if SVGs are created in complex ways (e.g. [this SelectedTick](https://github.com/elifesciences/elife-xpub/blob/develop/client/elife-theme/src/icons/SelectedTick.js) vs [UploadSuccess](https://github.com/elifesciences/elife-xpub/blob/develop/client/elife-theme/src/icons/UploadSuccess.js), where you would need to access a sub-path within the SVG in order to add a particular colour.

### Upload icons
These icons are not built to be re-used anywhere in our application:
- **Component Naming** - in an icon library, they are usually given more generic names  e.g. `UploadSuccess` is [called `CheckCircle` in the Material icons library](https://material.io/tools/icons/?icon=check_circle_outline&style=baseline), whereas our naming indicates that we only intend to use these within the `FileUpload` component
- **ID names within the SVG** - in these 3 components, [there are IDs within the SVG that specify the context in which the icon is used (i.e. dropzone)](https://github.com/elifesciences/elife-xpub/blob/develop/client/elife-theme/src/icons/Upload.js#L70)
- **Applying colour** - each icon is responsible for adding colours based on specific theme variables (e.g. [`UploadSuccess` adds `colorPrimary` to itself](https://github.com/elifesciences/elife-xpub/blob/develop/client/elife-theme/src/icons/UploadSuccess.js#L27)), but what if we want to re-use this icon elsewhere in our app with a different colour?  
Note: we do this with the cross icon - it is used in 2 places: a small white cross in SelectedItem & a larger grey cross in CalloutBox.

## Tasks
- [ ] Define a consistent way of creating custom SVGs - default size, default colours
- [ ] Define which components are responsible for styling (e.g. size and colour are added in context & therefore by the parent that's using the icon)
- [ ] Alter existing custom SVGs & add styling where they are being used
