### ISSUE TITLE
Iterate on People Picker functionality

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#485]
_As an author I want to be able to search by research focus in order to narrow down the list of results returned by the People Picker._

_As an author, I want to be able to see all the available information about a person so I can make an informed decision whether or not they would be appropriate to assess me work._

**Search**

- [x] #626 Search for matches anywhere in the person pod
- [ ] #627 Combine 'expertises' and 'focuses'
- [x] #628 Search for substrings
- [x] #629 Disable suggestion dropdown
- [ ] #630 Re-order keywords to bring matched term to the front
- [ ] #631 Make matched terms bold
- [ ] #582 Case fold accents

**Person Information**

- [ ] #633 Add an 'i' button to Person Pod component
- [ ] #635 Show full person profile within lightbox

**Bugs**
- [ ] #724 Fix layout issues in IE 11

**Comment by hdrury1** [comment]
Closing in favour of the milestone

**Comment by hdrury1** [comment]
Closing in favour of the milestone
