### ISSUE TITLE
Add data disclosure step to submission wizard

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#487]
**User Story:**

_As a submitter I want to be prompted to confirm I am happy with disclosing my data in order to have to option to decline and cancel my submission._

**Product requirements/Acceptance criteria:**

Functional:

- There should be an additional page added to the wizard to allow the submitter to confirm they are happy with our data disclosure agreement

- The page should pull in the article title, current date submitter's name and corresponding author's name captured on page 1 (if different)

- 'Privacy policy' should link to https://elifesciences.org/privacy-notice

- The user should not be able to proceed past this page without ticking the box and entering a value in the name input

- Validation message for the tick box should be 'We are unable to proceed without your consent.'

**Tasks**

- [x] #489 Create data disclosure page and connect to wizard
- [x] #519 Add date to disclosure page
- [x] #490 Store agreement in database

**Comment by jsms90** [comment]
Not sure what kind of process you wanna have for closing epics @hdrury1? But maybe do a brief click-through of the app & see that it conforms to product & design requirements as you would expect?
