### ISSUE TITLE
Create MECA export component

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#491]
In order to transfer data collected in xPub to an initial submission in eJP we will need a component that automates the process of producing a valid MECA file.

**See repo for sample files**: https://github.com/elifesciences/elife-xpub-meca

- [x] Generate `disclosure.pdf` #561 
- [x] Generate `article.xml` #562 
- [x] Generate ZIP archive with #563 
  - `article.xml`
  - `disclosure.pdf`
  - `cover_letter.html` (generated from `manuscript.coverLetter`)
  - the uploaded manuscript file 
  - `transfer.xml` 
  - `manifest.xml` (replace manuscript file name and mime-type).
- [x] Upload ZIP archive to eJP SFTP server #564 
- [x] Save ZIP archive to S3 for archive purposes #565 
- [x] Trigger the export from the `finishSubmission` mutation resolver #566

**Comment by diversemix** [comment]
@tamlyn / @hdrury1  ... do we also want a task for a callback endpoint ... i.e. something that eJP can callback on to give us the result of the import?
