### ISSUE TITLE
Add option to clear search box

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#540]
**User Story:**

_As a submitter I want to be able to easily clear my previous search term(s) in one action, rather than have to manually delete each character_

**Product requirements/Acceptance criteria:**

Functional:

- As soon as the search box is not empty, a cross icon should appear to the right of the text field

- Clicking the cross should clear the field

- An empty field should not have a cross icon

- Clearing the search box should also update the returned Person Pods (i.e. all Pods are returned in alphabetical order)

**Relevant links to design(s):**

![screen shot 2018-09-03 at 13 26 33](https://user-images.githubusercontent.com/17023702/44987251-79436480-af7e-11e8-9c52-79071f6f3e80.png)

**Tasks:**
- [x] Create button component & add to search box
- [x] Add handler so that clicking the cross button clears the input field
- [x] Fix positioning, so that button sits on top of `react-autosuggest`'s input field
- [x] Hook up clicking functionality to PeoplePicker so that it also updates the person pods
