### ISSUE TITLE
eJP Integration: Extend the `/people` API

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#545]
**User Story:**

The export tool will need to supply first & last name as well as email in the MECA file so eJP can reconcile editors to a user within their system (currently these are appearing in a sticky note)

Tasks: 
- [x] Design & change the RAML to define the interface. (Peter)
- [x] Implement the API and the UI within Journal.
- [x] Create & execute a 'back fill' script to populate the fields.

**Comment by diversemix** [comment]
Just submitted a PR .... may have to wait till Chris is back to get it approved. https://github.com/elifesciences/api-raml/pull/231

**Comment by diversemix** [comment]
@hdrury1 / @nlisgo ... can we check off any of these checkboxes?

**Comment by diversemix** [comment]
I'm going to assign myself to this to do the last item as we can now change the people picker as we are getting surname ... see https://api.elifesciences.org/people?type=executive&per-page=100

**Comment by diversemix** [comment]
Raised other issues so closing
