### ISSUE TITLE
Implement a production ready deployment

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#579]
## User Story

_As a Product Manager I want a production ready deployment of the application in order to test we are ready for real users and then to deploy to those users._

## Product requirements/Acceptance criteria

For this epic to be considered 'done' we should have achieved a deployment of eLife xPub within the eLife infrastructure on AWS this is production ready.

### Tasks
- [x] #658 Deploy ScienceBeam as a container alongside xPub
- [x] #618 Configure logging
- [ ] #692 Integrate with loggly

**Configuration**
_Please make sure that any secrets are sent securely to @giorgiosironi_
- [x] #616 Configure xPub to use S3
- [ ] #672 Configure SFTP for EJP integration
- [x] #673 Configure Mailer for failure alerts/notifications
- [ ] #620 Configure database connection details
- [ ] #619 Configure New Relic to monitor xPub

**Documentation:**
- [ ] #617 Add xpub to eLife playbook (aka Create a runbook)
- [ ] #671 Create more comprehensive in-app documentation

**Dependencies:**
- [x] #622 Create S3 buckets
- [ ] #623 Setup database in environments
- [x] Enable encryption
  - [ ] #704 on S3
  - [x] on database

**Infrastructure**
- [ ] #688 Create staging environment

**Comment by damnhipster** [comment]
We should consider creating a runbook to document steps to address issues such as https://github.com/elifesciences/elife-xpub/issues/608#issuecomment-422034556

**Comment by hdrury1** [comment]
Closing in favour of https://github.com/elifesciences/elife-xpub/milestone/1
