### ISSUE TITLE
Manuscript upload feature

### ISSUE THREAD

**Issue by jsms90** [elifesciences/elife-xpub#600]
New product requirements & designs coming in:
- [x] #560 remove manuscript preview from our codebase
- [x] #560 add warning about large files to the default state of the `FileUpload` component
- [x] #513 update error message for `FileUpload` component - red "Oops" & additional warning about file types
- [x] #520 store manuscript uploads in S3
- [x] #597 Show error message when user tries to upload wrong manuscript type
- [x] #605 re-enable upload resolver test
- [x] #595 Enforce 100MB file size limit on manuscripts

**Comment by jsms90** [comment]
Just created a new epic to keep track of the work that's going into this feature. It seems to be ballooning a little. I imagine this is a good indication that this needs to be added to the roadmap, so we can prioritise on Wednesday?

**Comment by jsms90** [comment]
@hdrury1 @gmaciocci So the latest product/design reqs specify 3 different UI states:

**Initial**
![screen shot 2018-09-06 at 12 54 49](https://user-images.githubusercontent.com/17023702/45155803-13e8b100-b1d4-11e8-8e8a-796c8783d1b4.png)

**Error**
![drop-zone-error](https://user-images.githubusercontent.com/17023702/44402856-da187900-a54a-11e8-9367-761d8e0ae3c9.png)

**Success**
![image](https://user-images.githubusercontent.com/15656538/45631738-7cb51080-ba93-11e8-9233-dc31836d6759.png)

(and for a while we also had a 4th state - **Progress**, which has been removed from first release)

---

So right now, we show the user the same **Error** view, regardless of the reason for the error.
1. If we only showed the "type of file" message to the user when this was the problem, it might help them to correct their mistake.
2. If we show them a "Files should be of this format & below this size" error message, when the actual problem comes from the server, they will probably think the issue is their fault when it's not.

Can I suggest that we split the **Error** view into 3 different types:
- User error
  - Size of file
  - Type of file
- Server error (e.g. fault with our app / internet connection goes down)

**Comment by jsms90** [comment]
Actually, just to clarify, what's in our app right now is this:

**Client-side error - e.g. file type, file size or number of files**
![image](https://user-images.githubusercontent.com/15656538/45635441-e4bc2480-ba9c-11e8-8f73-67fc3b22fb08.png)

**Server-side error**
![drop-zone-error](https://user-images.githubusercontent.com/17023702/44402856-da187900-a54a-11e8-9367-761d8e0ae3c9.png)

**Comment by hdrury1** [comment]
@jsms90 Client-side errors:

a) Error type = incorrect format

Message: "Oops! That file is not supported. Please try again. 
Files should be in .docx or .pdf format."

b) Error type = too big

Message: "Oops! Your file is too large. Please try again. 
Files should be no larger than 100MB"

c) Sever error

Message: "Oops! Unable to upload your file. Please try again.
If the problem persists please contact journal staff."

**Comment by diversemix** [comment]
Closing as done ages ago!
