### ISSUE TITLE
Configure xPub to use S3

### ISSUE THREAD

**Issue by damnhipster** [elifesciences/elife-xpub#616]
We are uploading files to S3 due to #520 and #565.

xPub needs to be configured to upload files to the correct bucket for the following environments:

- [x] Demo
- [x] Production

**Tasks:**
- [x] ensure AWS and bucket credentials can be picked up
- [x] ensure ZIP file can be uploaded to S3
- [ ] ensure manuscript can be uploaded to and downloaded from S3 - depends on #520

**Comment by diversemix** [comment]
We also need to check that node picks up the AWS config from inside the container here: `/home/elife/.aws/credentials:/root/.aws/credentials`

**Comment by diversemix** [comment]
@damnhipster ... deployed to production... issue now is that ORCID is not configured correctly :(

**Comment by damnhipster** [comment]
There's a bug where the manuscript isn't being archived correctly in the ZIP file. This should get addressed in #520
