### ISSUE TITLE
Configure xPub to use database

### ISSUE THREAD

**Issue by damnhipster** [elifesciences/elife-xpub#620]
Demo and Production are currently configured to use a postgres instance set up locally on the host, alongside the xPub application container. This is not a production ready solution.

Once we have a persistent, managed database for Demo and Production, we should configure the application to use it.

**Staging**:
- [x] add username, password and hostname for postgres to xpub
- [x] setup database using `npx pubsweet setupdb --clobber` and generate and store admin user secrets
- [x] Test out the environment

**Production**:
- [x] add username, password and hostname for postgres to xpub
- [x] setup database using `npx pubsweet setupdb --clobber` and generate and store admin user secrets
- [x] Test out the environment

**Tasks**:
- [ ] ~run migrations as part of deployment, and test them out in staging before pushing to production~
- [x] remove integration with local DB in demo environment

Considerations
- !!! **MAKE SURE PRODUCTION CONFIG IS NOT POSTED IN SLACK OR ANY UNENCRYPTED CHANNEL OF COMMUNICATION**; use something like keybase instead
- Use the recommended approach for `builder` applications to store the config, or use AWS Secrets Manager and configure xPub to fetch from there
- If there are network errors, they may be related to security groups, and VPC/subnet issues

**Comment by giorgiosironi** [comment]
Reference for [how we magically switch from RDS to a local `postgres` container](https://github.com/elifesciences/digests-formula/blob/master/salt/digests/init.sls#L78-L91) depending on whether RDS is present at all in an environment.

**Comment by giorgiosironi** [comment]
I assign myself (plus someone else on the application side) to provide support for the formula changes.

**Comment by diversemix** [comment]
@damnhipster and @dryhten will start work on this soon in the `prod` environment as demo is being switched to staging.

**Comment by damnhipster** [comment]
- [ ] `db.end` error when running the migration
- [ ] GraphQL error when visiting staging when not logged in

**Comment by damnhipster** [comment]
Tested Staging and Production environments.

These can be found at the following URLS:

|Environment|Link|
|-|-|
|Staging|https://staging--xpub.elifesciences.org/|
|Production|https://xpub.elifesciences.org/|
