### ISSUE TITLE
Configure xPub using builder

### ISSUE THREAD

**Issue by damnhipster** [elifesciences/elife-xpub#621]
All the configuration for xPub is checked into `/config`, including secrets and endpoints. This isn't viable for production.

Production config can be done using one of the following methods:
- Inject a config.js file into the application container during deployment, using `builder`. This file should be stored somewhere secure so it can be edited in the future if necessary
- Configure xPub to pickup environment variables, and use `builder` to set them up. Store environment variables securely, either on Jenkins or some other method

**Tasks:**
- [ ] Get secrets for production
  - [ ] Sciencebeam URL
  - [ ] SFTP details for EJP integration
  - [ ] email address for Mailer for failure alerts/notifications
  - [ ] ORCID details
- [ ] Put secrets in a private gist and send to @giorgiosironi
- [ ] Update elife-xpub-formula to forward config to the container

**Comment by damnhipster** [comment]
Put secrets in a private gist and send to @giorgiosironi

**Comment by giorgiosironi** [comment]
References:

- most of the configuration is [passed through a single `NODE_CONFIG` environment variable](https://github.com/elifesciences/elife-xpub-deployment/blob/develop/docker-compose.yml#L17-L38) at the moment
- this variable is filled in with [environment variables made available to the `elife` user on the host node](https://github.com/elifesciences/elife-xpub-formula/blob/master/salt/elife-xpub/init.sls#L26-L28)
- pillars [default to fake values](https://github.com/elifesciences/elife-xpub-formula/blob/master/salt/pillar/elife-xpub.sls) but are overridden with [real ones from a monolithic repository](https://github.com/elifesciences/builder-private/blob/master/pillar/elife-xpub.sls) on all AWS nodes

**Comment by damnhipster** [comment]
Addressed by separate issues in #579 

The proposal for configuration has been detailed within the comments of #667
