### ISSUE TITLE
Integration with eLife

### ISSUE THREAD

**Issue by tamlyn** [elifesciences/elife-xpub#632]
**Product requirements/Acceptance criteria:**

Functional:
- Signing in to eLife also signs the user into xPub and vice versa. \
- Clicking 'Submit my research' from the eLife homepage redirects the user to their xPub dashboard (if logged in) or to the xPub log in (if not logged in).

![image](https://user-images.githubusercontent.com/15656538/45893065-02053180-bdc2-11e8-9b54-b60ea93d6c3f.png)

**Tasks:**
- [x] #554 Derisk authenticating against Profile Service
- [x] #634 Update xPub Login page
- [x] #636 Discussion: using profiles service instead of users table
- [x] #637 Create Journal endpoint to generate JWT for xPub
- [x] #665 Profiles service integration
- [x] #678 Implement JWT exchange functionality
- [x] #670 Refactor orcidDetails query
- [x] #721 Update iss in `builder-private`

**Further tasks**:
The following task can't be done until launch day so is not considered part of this epic.
-  Update 'Submit my research' link to point to xPub

**Comment by diversemix** [comment]
Still outstanding is: https://github.com/elifesciences/elife-xpub/issues/721

**Comment by diversemix** [comment]
Closing as done ages ago!
