### ISSUE TITLE
Show full person profile within modal

### ISSUE THREAD

**Issue by hdrury1** [elifesciences/elife-xpub#635]
### Product reqs
- Clicking on the 'i' button within a person pod should open up a modal
- The lightbox should contain all of the information on a person collected from the eLife API
- The information should be separated into its component fields
- Clicking 'Add Editor' should close the lightbox and select the person (the same as hitting the '+' button without opening the modal
- Clicking 'Cancel' should close the modal with no changes to the UI
- ~Clicking 'Back' on the browser should close the modal~ - product req removed
- ~Clicking outside of the lightbox should close the modal~ - deprioritised & now captured as issue #1121 

### Designs
https://app.zeplin.io/project/5bacf042615a8b6e20e84a5f/screen/5bc48bf829495f5fbbfe62ed

<img width="859" alt="screen shot 2018-11-12 at 16 19 06" src="https://user-images.githubusercontent.com/17023702/48360291-d2bec280-e696-11e8-9507-18df0c75d893.png">

### Tasks
- [x] Create PersonInfo component for use within ModalDialog
- [x] Refactor existing codebase to store research focuses & expertises separately from each other, so they can be displayed separately on the modal
- [x] Add FullPersonInfoModal into PersonPod - involves making it stateful, in order to keep track of whether modal is open/closed
- [x] Connect FullPersonInfoModal into EditorsPage (version with Accept button = "Remove Editor") & PeoplePickerControl (version with Accept button = "Add Editor")

**Comment by hdrury1** [comment]
I've just realised there are two different contexts for this modal, one within the People Picker and one within the editor page since the 'i' button is an attribute of the Person Pod component and the component appears in more than one place:

<img width="912" alt="screen shot 2018-11-15 at 12 46 13" src="https://user-images.githubusercontent.com/17023702/48553876-bad48200-e8d4-11e8-9245-584c832b4f54.png">

In this instance it doesn't make sense for the modal to have the 'Add Editor' button, so we may need to abstract this out? @chugginselifesciences in this context all we need to be able to do is close the modal right?

**Comment by chugginselifesciences** [comment]
Yes I imagined the modal would simply have "remove editor" instead of "add editor".

**Comment by jsms90** [comment]
Currently getting this issue:
![image](https://user-images.githubusercontent.com/15656538/48706398-12842d80-ebf4-11e8-93ca-1430ab7fa3cf.png)

I'm guessing this is to do with trying to add a second modal (this one) on top of the People Picker modal, given the way that we are keeping track of modal state:
https://github.com/elifesciences/elife-xpub/blob/1d1590e2f9fd62aea845d8f9b3349c0753fa7f79/app/components/ui/molecules/ModalHistoryState.js#L4-L21

**Comment by jsms90** [comment]
Rather than pushing directly to `history`, I'm thinking we should be hooking this up to `react-router`, so each modal has its own route.

[React training docs](https://reacttraining.com/react-router/web/example/modal-gallery) seem to do this, as well as [examples in `react-modal`](https://github.com/reactjs/react-modal/blob/f715a69e31b00eaf7912595a9bd2d22ab5cecdb3/examples/basic/react-router/index.js)

**Comment by hdrury1** [comment]
Sounds good @jsms90.

**Comment by jsms90** [comment]
After walking @SemraSh and @damnhipster through the problem today, we started looking through the `history` (npm package) source code, trying to understand where the above error is coming from & why.

This is the location in the source code:
https://github.com/ReactTraining/history/blob/master/modules/createBrowserHistory.js#L155-L164

You can see further down in the `history.push` method, that it's using the HTML5 history API under the hood. More specifically, it's [calling `history.pushState`](https://github.com/ReactTraining/history/blob/master/modules/createBrowserHistory.js#L180) - see [MDN docs for pushState](https://developer.mozilla.org/en-US/docs/Web/API/www.google.co.uk#The_pushState()_method)

So, after a little bit of playing with the HTML5 history API, it seems like it allows you to push a state object to the same path for a 2nd time:
![image](https://user-images.githubusercontent.com/15656538/48852879-3ab38e00-eda6-11e8-9919-af6a196ab9da.png)

but for whatever reason the `history` npm package does not.

So we're raising an issue on that repo to query what this warning is about.

In the meantime, we're thinking that it would be better to turn the people picker page into its own route, rather than keeping it as a modal.

**Comment by jsms90** [comment]
This issue now depends on #1081

**Comment by jsms90** [comment]
We want to keep these both as modals. So we're not refactoring the editors page in the codebase & making the People Picker its own page (i.e. close #1081).

Which means that we have to find another solution in order to work around [this limitation from `history`](https://github.com/elifesciences/elife-xpub/issues/635#issuecomment-439873088) - i.e. we can't have 2 modals on top of one another by pushing a 2nd state object to `history.location`.

In order to achieve 2 modals on top of one another, this product req has been removed:
> Clicking 'Back' on the browser should close the modal

Instead, we will:
- keep the implementation which is connected to `react-router` (i.e. history) for the People Picker modal
- (also keep the `react-router` implementation for the thank you modal at the end of the wizard
- introduce a new modal implementation, which is not connected to history & therefore does not interact with the browser's forward/back buttons, for the full person info modal

**Comment by jsms90** [comment]
@hdrury1, we've altered the top comment to reflect the removal of this product req & we've broken down the issue into sub tasks. Hope that helps to clarify our new intentions.

@Cooryd @damnhipster See top comment for how we're intending to approach this now :smile:

**Comment by hdrury1** [comment]
Makes sense to me! Thanks to @Cooryd for the suggested solution.
