### ISSUE TITLE
Create elife-xpub--staging

### ISSUE THREAD

**Issue by giorgiosironi** [elifesciences/elife-xpub#688]
**User Story:**

_As a project manager or developer I want to perform exploratory testing and simulations in an isolated `staging` environment in order to understand what the application is doing, demonstrating functionality and find bugs._

**Product requirements/Acceptance criteria:**

Non-functional:

- there is an application running at staging--xpub.elifesciences.org
- this application is configured to talk with continuumtest--journal.elifesciences.org and other `continuumtest` resources (current staging environment)
- uses RDS and other real _internal_ dependencies
- uses ORCID sandbox and other sandboxes for _external_ dependencies

** Tasks **
- [x] https://github.com/elifesciences/elife-xpub/pull/695
- [x] https://github.com/elifesciences/builder-configuration/pull/4
- [x] https://github.com/elifesciences/builder-private/pull/247
- [x] https://github.com/elifesciences/builder/pull/401
- [x] creation
- [x] add to pipeline
- [x] `demo` removal

**Comment by giorgiosironi** [comment]
- [ ] https://github.com/elifesciences/elife-xpub/pull/695
- [ ] https://github.com/elifesciences/builder-configuration/pull/4
- [ ] https://github.com/elifesciences/builder-private/pull/247
- [ ] https://github.com/elifesciences/builder/pull/401

**Comment by giorgiosironi** [comment]
After all PRs are in, I will create the stack and add it to the pipeline.

**Comment by giorgiosironi** [comment]
Keep this open until all references to `demo` are removed, but shouldn't block anyone as `staging` is there and deployed to by the pipeline.

**Comment by diversemix** [comment]
@giorgiosironi ... do you have a list of references to demo? My list is
* `elife-xpub-deployment:/Jenkinsfile`
* `elife-xpub:/config/default.js`
* `elife-xpub:.gitlab-ci.yml`

**Comment by giorgiosironi** [comment]
Apart from `.gitlab-ci.yml` which is probably using `demo` with a different meaning, all the rest has been removed.
