### ISSUE TITLE
Create uploadManuscript mutation and resolver

### ISSUE THREAD

**Issue by tamlyn** [elifesciences/elife-xpub#69]
This should:
- [x] save the document somewhere (on the server is fine for now)
- [x] send it off to ~~INK~~ ScienceBeam for processing
- [ ] ~~create a {submission,article,manuscript} entity in the database when it completes~~
- [ ] ~~return the new entity to the client~~

~~Adapt ink-server component if possible.~~
