### ISSUE TITLE
Deploy PRs with an Helm chart

### ISSUE THREAD

**Issue by giorgiosironi** [elifesciences/elife-xpub#938]
Split from https://github.com/elifesciences/elife-xpub/issues/675

**User Story:**

_As a developer/tester/operator I want a reproducible way to deploy containers on Kubernetes in order to reliably create demo environments of new PRs._

**Product requirements/Acceptance criteria:**

Non-functional:
- [x] a Helm chart it stored in `elife-xpub-formula` alongside the Salt setup
- [ ] ~a build does some minimal validation and pushes it at `s3://demo-elife-kubernetes-helm` or similar chart~ https://github.com/elifesciences/issues/issues/4587
- [x] the chart can be used by `elife-xpub`'s build to create a new environment
- [ ] ~the Helm chart contains a throwaway `postgres` container (not stateful)~ https://github.com/elifesciences/elife-xpub/issues/938
- [x] post a commit status with link to the review environment (from https://github.com/elifesciences/elife-xpub/issues/938)
- [x] clean old environments in some way

**Comment by giorgiosironi** [comment]
Chart is good for use on Jenkins, but Jenkins needs to solve some setup first (having an authenticated Helm installed talking to the right cluster).

**Comment by giorgiosironi** [comment]
Attempting to integrate a proof of concept in https://github.com/elifesciences/elife-xpub/pull/985

**Comment by giorgiosironi** [comment]
Working on https://alfred.elifesciences.org/job/process/job/process-clean-xpub-environments/ which will be necessary to free resources on the cluster.

**Comment by giorgiosironi** [comment]
Merged on the xpub side.
